### ISSUE TITLE
Module: Implement for Tuple

### ISSUE THREAD

**Issue by dcvz** [tracel-ai/burn#1046]
### Feature description

Implementing Module support for Tuple

### Feature motivation

Would allow syntax such as:

```rust
#[derive(Module, Debug)]
pub struct UNetMidBlock2D<B: Backend> {
    resnet: ResnetBlock2D<B>,
    attn_resnets: Vec<(AttentionBlock<B>, ResnetBlock2D<B>)>,
}
```

### Workaround

Use struct instead of tuple.

**Comment by antimora** [comment]
Would a workaround of using struct work in this case? Suggesting in case if someone is stuck on this issue.

**Comment by dcvz** [comment]
> Would a workaround of using struct work in this case? Suggesting in case if someone is stuck on this issue.

Yup! That’s the workaround I’ve gone with but raised the issue after a conversation with Nathaniel.

**Comment by antimora** [comment]
Done via #1186
