### ISSUE TITLE
Slice bug on LibTorch backend

### ISSUE THREAD

**Issue by wcshds** [tracel-ai/burn#1055]
Here is the code.
```Rust
type Backend = LibTorch;

let tensor = Tensor::<Backend, 1, Int>::from_data([1, 2, 3, 4, 5]);
let tensor = tensor
    .clone()
    .slice([0..3])
    .equal(tensor.clone().slice([2..5]));
println!("{}", tensor);
```

Sometimes it panics.
![image](https://github.com/tracel-ai/burn/assets/8537285/9ad9a976-4454-4960-b837-9ff68f27f5b8)

**Comment by wcshds** [comment]
It seems that calling the `clone()` again after the second `slice()` could serve as a temporary workaround for this issue.
```Rust
type Backend = LibTorch;

let tensor = Tensor::<Backend, 1, Int>::from_data([1, 2, 3, 4, 5]);
let tensor = tensor
    .clone()
    .slice([0..3])
    .equal(tensor.clone().slice([2..5]).clone());
println!("{}", tensor);
```

**Comment by nathanielsimard** [comment]
I'm gonna work on this, it's probably at the source of some data corruption we have https://github.com/tracel-ai/burn/issues/877

**Comment by nathanielsimard** [comment]
@wcshds added the fix, can you validate if it works with your model?

**Comment by wcshds** [comment]
@nathanielsimard Thank you! Now it works.
