### ISSUE TITLE
Being able to collect backend-comparison benchmarks

### ISSUE THREAD

**Issue by nathanielsimard** [tracel-ai/burn#1072]
The goal of this issue is to allow users to share their benchmark results with the community so that we can report how fast burn is running on a variety of hardwares.

- [x] Create a web service where users can upload their results. We should have a github auth to ensure to a minimum the validity of the data.
- [x] Upload the data from a CLI (and run the benchmark from the CLI as well). We could code that CLI directly in `backend-comparison`.

**Comment by syl20bnr** [comment]
Done 🎉
