### ISSUE TITLE
Being able to visualize backend-comparison benchmarks

### ISSUE THREAD

**Issue by nathanielsimard** [tracel-ai/burn#1073]
We should be able to plot graphs to visualize the bencmarks from users with some aggregations:

- [x] By CPU type (e.g i7 13700U)
- [x] By GPU type (e.g Nvidia 3700 RTX)
- [x] By Backend
- [ ] By Backend configuration (Precision, Graphics API, etc.)
- [x] By OS
- [x] By users
- [ ] Etc.

**Comment by syl20bnr** [comment]
Done 🎉
