### ISSUE TITLE
Ndarray backend Tensor::swap_dims bug

### ISSUE THREAD

**Issue by PonasKovas** [tracel-ai/burn#1119]
**Describe the bug**
When using the `NDArray` backend, `swap_dims` method of `Tensor` doesn't work as expected.

**To Reproduce**
```rust
use burn::{
    backend::NdArray,
    tensor::{Float, Tensor},
};

fn main() {
    type B = NdArray;

    let v1 =
        Tensor::<B, 2, Float>::from_data([[1., 2.], [3., 4.]]).swap_dims(0, 1);
    println!("{}", v1);
    let v2: Tensor<B, 1> = v1.flatten(0, 1);
    println!("{}", v2);
}

```
```
Tensor {
  data:
[[1.0, 3.0],
 [2.0, 4.0]],
  shape:  [2, 2],
  device:  Cpu,
  backend:  "ndarray",
  kind:  "Float",
  dtype:  "f32",
}
Tensor {
  data:
[1.0, 2.0, 3.0, 4.0],
  shape:  [4],
  device:  Cpu,
  backend:  "ndarray",
  kind:  "Float",
  dtype:  "f32",
}
```

**Expected behavior**
`v2` should be `[1, 3, 2, 4]`, not `[1, 2, 3, 4]`.

Depending on the complexity of the underlying problem, I might be able to contribute and help fix this issue, if someone points me in the correct direction.

**Comment by gzsombor** [comment]
Maybe, I misunderstand you, but I've tried to reproduce it with a test case - [here ](https://github.com/gzsombor/burn/commit/b07e42a9a28f5bc976d3bd148cb9dbfdab610955), but it seems to be working, on all of the backends.

**Comment by PonasKovas** [comment]
@gzsombor It works correctly with `to_data()` for me too, the problem probably lies within `flatten()` then.

**Comment by gzsombor** [comment]
For me, this:
```
use burn_ndarray::{NdArray, NdArrayDevice};
use burn_tensor::{Float, Tensor};


fn main() {
    type B = NdArray;

    let v1 =
        Tensor::<B, 2, Float>::from_data([[1., 2.], [3., 4.]], &NdArrayDevice::Cpu).swap_dims(0, 1);
    println!("{}", v1);
    let v2: Tensor<B, 1> = v1.flatten(0, 1);
    println!("{}", v2);
}
```

writes out: 

```
Tensor {
  data:
[[1.0, 3.0],
 [2.0, 4.0]],
  shape:  [2, 2],
  device:  Cpu,
  backend:  "ndarray",
  kind:  "Float",
  dtype:  "f32",
}
Tensor {
  data:
[1.0, 3.0, 2.0, 4.0],
  shape:  [4],
  device:  Cpu,
  backend:  "ndarray",
  kind:  "Float",
  dtype:  "f32",
}
```

I guess, this bug is already fixed in Git - and as the API is a slightly different, than in your example - so if you could upgrade to git dependency, then this will be solved for you too.

**Comment by PonasKovas** [comment]
Yep, works fine on the git version.
