### ISSUE TITLE
Refactor Reduce Autotune

### ISSUE THREAD

**Issue by louisfd** [tracel-ai/burn#1175]
In WGPU we can autotune Reduce. But Reduce is not a specific operation but rather an algorithmic strategy which encompasses, sum, prod, mean, max/min, argmax/argmin, etc. The list of supported Reduce operations for autotune is growing (see #1136, #1173) and each time it demands to duplicate the whole autotune config file. 

In fact, I think we can safely assume that when a Reduce kernel is the best for one of the Reduce operations, it is extremely likely that it will be the best for any Reduce operation on the same device/shapes. Therefore they could share their key and part of their config file. 

We need to come up with a design where adding autotune support for a reduce operation is more light, while ensuring that even though the key is shared the autotune always computes the kernel of the appropriate operation in the end.

**Comment by nathanielsimard** [comment]
This is especially important to support fusion operations as well, where any element wise fused operation can share the same key.

**Comment by louisfd** [comment]
Blocked by #1114
