### ISSUE TITLE
Update wgpu version

### ISSUE THREAD

**Issue by nathanielsimard** [tracel-ai/burn#1222]
We encountered a notable performance issue upon updating to the new wgpu version `0.19.0`. As a result, we had to revert to the previous version in this pull request: https://github.com/tracel-ai/burn/pull/1221

Moving forward, we need to have a strategy to update our wgpu backend to align with the latest upstream changes without negatively affecting performance.

**Comment by syl20bnr** [comment]
At the time of writing wgpu 0.19.3 has still the performance regression in compute shaders.

Closing this issue in favor or https://github.com/tracel-ai/burn/issues/1546 where there is a bit more information.

@nathanielsimard feel free to update the other issue with additional info if necessary.
