### ISSUE TITLE
code is faild to run after update the version

### ISSUE THREAD

**Issue by twhice** [tracel-ai/burn#1224]
**Describe the bug**

panicked unexpectedly after i update the version from 0.11 to 0.12

```
thread 'main' panicked at C:\Users\twhice\.cargo\registry\src\rsproxy.cn-0dccff568467c15b\burn-autodiff-0.12.0\src\ops\tensor.rs:1598:44:
called `Option::unwrap()` on a `None` value
```

**To Reproduce**

[here](https://github.com/twhice/learn-deep-learning/commit/c9bd611ae8090a1e2613883863d02dc0fe2fa6a0)is the project

**Expected behavior**

the code run well as i didnt update the version of burn from 0.11 to 0.12

my toolchain:

- rustc 1.75.0 (82e1608df 2023-12-21)

- stable-x86_64-pc-windows-msvc

**Comment by nathanielsimard** [comment]
This is a bug indeed, but also linked with a breaking change, if you were on version 0.11.1 before, you can use the function `powf_scalar` for the same behavior and it should fix your problem.

But thanks for pointing that out, we will fix this today 😅

**Comment by twhice** [comment]
> This is a bug indeed, but also linked with a breaking change, if you were on version 0.11.1 before, you can use the function `powf_scalar` for the same behavior and it should fix your problem.
> 
> But thanks for pointing that out, we will fix this today 😅

ok, using `powi_scalar` fixs my problem

one more thing, it's already 23:30 in my area , please fix this in today (hh)
