### ISSUE TITLE
Support signed value for `Tensor::arange`

### ISSUE THREAD

**Issue by Nikaidou-Shinku** [tracel-ai/burn#1234]
### Feature description

Currently `Tensor::arange` accepts a `Range<usize>`, which can only generate unsigned value.
It will be great if we also support signed value.

### Suggest a Solution

Since the `usize` value is converted into `i64` by `(i as i64).elem()` in `FloatTensorOps::float_arange_step`, maybe we can make `Tensor::arange` directly accepts a `Range<i64>`.
If that's okay, I can submit a PR for it.

**Comment by louisfd** [comment]
It's a good idea! Please go ahead
