### ISSUE TITLE
WASM Support: Install burn without installing libsqlite3

### ISSUE THREAD

**Issue by mfranzs** [tracel-ai/burn#1257]
**Describe the bug**
Attempting to bundle burn into a WASM rust library results in a compile-time failure because `libsqlite3` is included 

![CleanShot 2024-02-04 at 13 04 54@2x](https://github.com/tracel-ai/burn/assets/953103/69cc58cd-4ac7-42a9-809e-c928f8d8f3e0)

**To Reproduce**
Installing burn with this snippet (attempting to disable the sqlite flag) causes the failure.

```
[dependencies.burn]
version = "0.12.1"
default-features = false
features = ["std", "train", "ndarray"]

[dev-dependencies.burn]
version = "0.12.1"
default-features = false
features = ["std", "train", "ndarray"]

```

**Expected behavior**
Disabling the sqlite feature should not attempt to install libsqlite3.

Looking at the dependency tree, this is coming from:
burn-core => burn-dataset => r2d2_sqlite => rusqlite => libsqlite3-sys

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: N/A - All WASM
 - Version: 0.12.1

**Additional context**
I see an example repo that seems to be avoiding this issue, but I'm not sure how. Thanks in advance!

**Comment by AlexErrant** [comment]
In the above PR [I change burn-train's Cargo.toml](https://github.com/tracel-ai/burn/pull/938/files#diff-6a35a98c03bc063fbb33e367f90ce1f477a9b10fc9508313986c7706c7558e17) default featureset to

```
default = ["metrics", "tui", "burn-core/default", "burn-core/dataset"]
```

while simultaneously doing

```
burn-core = { path = "../burn-core", version = "0.12.0", default-features = false }
```

This removes the `burn-dataset` dependency from `burn-core`. Perhaps this is enough to build to wasm.

**Comment by antimora** [comment]
Train in wasm is not supported. You should build with default features disabled, which would force you the library be no-std compatible.

**Comment by one-for-all** [comment]
@antimora Hi, is there plan to support training in wasm?

**Comment by one-for-all** [comment]
never mind. I think I have answer here #1254
