### ISSUE TITLE
Refactor: move all crates to `crates` folder

### ISSUE THREAD

**Issue by nathanielsimard** [tracel-ai/burn#1263]
Move all crates to the `crates` folder.

- burn-autodiff
- burn-candle
- burn-common
- burn-compute
- burn-core
- burn-dataset
- burn-derive
- burn-fusion
- burn-import
- burn-ndarray
- burn-no-std-tests
- burn-tch
- burn-tensor
- burn-traing
- burn-tensor-testgen
- burn-wgpu
- burn

**Comment by antimora** [comment]
Well, we are doing it. Can we remove `burn-` prefix as well? We can leave the names with `burn-` as well. It's often a pain to keep typing `burn-` to cd.

**Comment by syl20bnr** [comment]
I understand that's a bit tedious but I believe that prefix is important and it keep the folder name  consistent with the crate name.

Alternative proposition: we name the folder `burn-crates` and then we leave the prefix in the crate folders.

**Comment by nathanielsimard** [comment]
I prefer to keep the structure `crates/burn-{name}` since this is their crate name after all and it would be confusing to have something else.

**Comment by antimora** [comment]
@nathanielsimard, I ask you to reconsider keeping `burn-` prefix. It adds zero value and I don't think there would be a confusion. Navigating and reading will be much easier. 

Take this project for example: https://github.com/BurntSushi/ripgrep/tree/master/crates 

Here is the root of the project: https://github.com/BurntSushi/ripgrep/tree/master

I think the examples should be remain at the top root folder and should not be under crates.

I would like opinion of others here: @louisfd @syl20bnr @ashdtu @laggui

**Comment by syl20bnr** [comment]
Hmmm we need to discuss about this.

If we remove the prefix, I suggest moving all the crates to the `crates` folder, and they should all have the `burn-` prefix in `Cargo.toml` for consistency. The only crate impacted by this convention is `backend-comparison`, which could be renamed to `benches`, resulting in `burn-benches` in its Cargo file.

We would also move the books to `books` folder, so `burn-book` does not appear at the root level.

**Comment by laggui** [comment]
> @nathanielsimard, I ask you to reconsider keeping `burn-` prefix. It adds zero value and I don't think there would be a confusion. Navigating and reading will be much easier.
> 
> Take this project for example: https://github.com/BurntSushi/ripgrep/tree/master/crates
> 
> Here is the root of the project: https://github.com/BurntSushi/ripgrep/tree/master
> 
> I think the examples should be remain at the top root folder and should not be under crates.
> 
> I would like opinion of others here: @louisfd @syl20bnr @ashdtu @laggui

In your example it wasn't clear at first but some crates actually seem to be "standalone" like `globset`, `ignore` and `grep` while the others are extensions to the `grep` crate and have that in their prefix. So to me the use-case seems a little different at first.

For consistency I think it makes sense to keep the prefix, but I don't have that strong of an opinion on this. Just giving my 2c.

**Comment by nathanielsimard** [comment]
`crates/{crate-name}` is better for consistency,  but `crates/{crate-name-minus-burn}` is better for manually navigating the codebase. The thing is there are exeption like `burn` which isn't prefixed by burn (no `burn-burn`) and `backend-comparison`.

**Comment by antimora** [comment]
Alright, I surrender my position. May my fingers find mercy 😄

**Comment by syl20bnr** [comment]
OK, happy that we reached a consensus. Consistency is important indeed.

I am starting on this one.
