### ISSUE TITLE
Chore: Use Candle's published crate version instead of git source code

### ISSUE THREAD

**Issue by antimora** [tracel-ai/burn#1299]
There are several unpublished Candle core features needed to fix issues with PyTorchRecorder (top level key, latest pt file format, fortran contiguous layout). For now, we would like to use a fix git version and once Candle publishes, we switch the version. This issue to track before our release.

**Comment by nathanielsimard** [comment]
@antimora if we use a git version, it's impossible to deploy burn to crates.io, that's why we are sticking with a fixed version.

**Comment by antimora** [comment]
Spoke offline and decided to wait for a new Candle release. Closing it.
