### ISSUE TITLE
Can't load `squad` dataset. Load huggingface datasets fail. 

### ISSUE THREAD

**Issue by sunwenming** [tracel-ai/burn#1351]
**Describe the bug**
https://github.com/tracel-ai/burn/blob/261e7eca1d2f36cf70495c08274f002898913ab8/crates/burn-dataset/src/source/huggingface/importer.py#L105
AttributeError: 'NoneType' object has no attribute 'id'

**To Reproduce**

1. Load `squad` dataset
```
let dataset: SqliteDataset<SquadItem> = HuggingfaceDatasetLoader::new("squad")
            .dataset(split)
            .unwrap();
```

**Expected behavior**

1. Load squad dataset success.

**Additional context**

[datasets.Dataset.to_sql](https://hf-mirror.com/docs/datasets/v2.17.1/en/package_reference/main_classes#datasets.Dataset.to_sql)

**Comment by laggui** [comment]
Just replicated on my end. Small issue with the python hf dataset importer, will submit a quick PR for that.
