### ISSUE TITLE
Add `nonzero` tensor op

### ISSUE THREAD

**Issue by laggui** [tracel-ai/burn#1373]
Getting the indices of truth elements in a tensor is pretty useful. This is usually done by `nonzero()` or `argwhere()` ops.

**Example**

```rust
let x = Tensor::arange(0..6 as i64, &device).reshape(Shape::new([2, 3]));
let mask = x.greater_elem(1);
mask.nonzero()
// [[0, 0, 1, 1, 1], [1, 2, 0, 1, 2]]
```

**Comment by antimora** [comment]
This might be related to `bool()` operator in this PR: https://github.com/tracel-ai/burn/pull/1402

We can use `bool()` for mask.
