### ISSUE TITLE
SIMD support

### ISSUE THREAD

**Issue by bioinformatist** [tracel-ai/burn#1377]
### Feature description

Shall we add a new backend `burn-simd` to Burn?

### Feature motivation

We already have `burn-ndarray` to support `no_std`, but `ndarray` doesn't seem to be fast enough. Besides, I'm not sure that if `candle` is fast enough on CPU and if they have any plan for `no_std`.

### (Optional) Suggest a Solution

If such a backend is required, which level of SIMD Rust binding should we use: portable SIMD or Intel's intrinsic APIs from `core::arch`? Portable SIMD is slightly slower due to some [memory layout issues](https://doc.rust-lang.org/core/simd/struct.Simd.html#layout-1). The intrisic instructions provide the fastest performance, but adapting them for various hardware architectures (e.g., _SSE_, _AVX2_, _AVX512_, etc.) might take significant effort. Tensors with a length that is not a **power of `2`** also need to be split for computation before being merged.

**Comment by antimora** [comment]
Candle backend supports SIMD. It even works for WASM. See image classifier example built for SIMD.

**Comment by bioinformatist** [comment]
> Candle backend supports SIMD. It even works for WASM. See image classifier example built for SIMD.

Yes, it [did](https://github.com/huggingface/candle/blob/main/candle-core/src/cpu/mod.rs). 

I didn't notice it before. Let me have a try on CPU with Candle backend. I have been using the NdArray backend for several months.

**Comment by antimora** [comment]
Let me know if it works for you and we should close this ticket.

**Comment by bioinformatist** [comment]
It seems Candle is enough now. @antimora Thanks a lot!
