### ISSUE TITLE
tensor `.bool()` operator 

### ISSUE THREAD

**Issue by antimora** [tracel-ai/burn#1395]
We have `float()` and `int()` but missing `bool()` (similar to [pytorch's](https://pytorch.org/docs/stable/generated/torch.Tensor.bool.html))  

### Feature description

Similar conversation as PyTorch's https://pytorch.org/docs/stable/generated/torch.Tensor.bool.html

### Feature motivation

To be feature complete. We explicitly do this with `any()` and `all()` operator.

**Comment by nathanielsimard** [comment]
It was an explicit decision not to support that function, as numeric comparison functions exist and provide a clearer indication of how the boolean conversion should be performed (e.g., `let my_bool = tensor.not_equal(0)`). Though I'm open into supporting `bool` as long as the behavior is intuitive.

**Comment by laggui** [comment]
I'm not against adding the `.bool()` operator, but I personally prefer explicit conversions so I agree with @nathanielsimard . As opposed to other types, the behavior doesn't feel very intuitive.

That's still just my personal opinion, but I'm pretty sure I never had to convert anything through `.bool()` in my experience.

**Comment by antimora** [comment]
@nathanielsimard , @laggui , this is for completeness. `.all()` on `Int` and `Float` tensors already uses implicit conversation. I am not sure if this was intended but this how PyTorch and NumpPy behaves for `.all()`: https://pytorch.org/docs/stable/generated/torch.all.html

**Comment by laggui** [comment]
Ahh ok I didn't realize `.all()` was implemented for all types.

No objections in that case :)
