### ISSUE TITLE
Visualize benchmarks in a single table view

### ISSUE THREAD

**Issue by akhildevelops** [tracel-ai/burn#1440]
### Feature description
Display benchmark results as a single table in the console

### Feature motivation
It's pain to see and scroll through results across combinations of benchmark types and backends.

**Comment by nathanielsimard** [comment]
@syl20bnr is working in this ;)

**Comment by akhildevelops** [comment]
Cool if it's only a dashboard then I would also suggest to have a table with results in the console after benchmark runs. Lemme know what you think ?

**Comment by syl20bnr** [comment]
That's a great idea !
