### ISSUE TITLE
Onnx import gives a filenotfound error when building with `cargo install`

### ISSUE THREAD

**Issue by mrvollger** [tracel-ai/burn#1501]
**Describe the bug**
This might not be a `burn-rs` issue but instead an issue with how cargo packages data in `install` vs build, but I am hoping that is not the case and I can get some help here.

I have successfully built a package that imports a bunch of onnx models, passes all the tests, and runs fine in release mode, etc. However, when I then publish the package and install it via `cargo install` it seems that the onnx rs files that are built in my build.rs result in FileNotFound panics that looks something like:
```
thread 'main' panicked at /tmp/cargo-installD74X3I/release/build/fibertools-rs-817dca3dd5ecc1ff/out/m6a_burn/two_zero.rs:36:14:
```
Where `two_zero.rs` is a module that is being built by burn_import in `build.rs`

Happy to hear any thoughts anyone might have and thanks in advance!

**To Reproduce**
```
# clone to get test data
git clone https://github.com/fiberseq/fibertools-rs
cd fibertools-rs

# install from cargo
cargo install --all-features fibertools-rs

# test and get error
RUST_BACKTRACE=1 ft predict-m6a -t 12 tests/data/all.bam /dev/null
```
The error 
```
thread 'main' panicked at /tmp/cargo-installD74X3I/release/build/fibertools-rs-817dca3dd5ecc1ff/out/m6a_burn/two_zero.rs:36:14:
Record file to exist.: FileNotFound("No such file or directory (os error 2)")
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: fibertools_rs::m6a_burn::BurnModels<B>::new
   4: fibertools_rs::predict_m6a::read_bam_into_fiberdata
   5: ft::main
```

**Comment by antimora** [comment]
If your build, you can control the out directory. It defaults to target build directory. You can change this via `.out_dir` builder param.

You can see this SqueezeNet example where I made sure the weights our copied somewhere else: 

https://github.com/tracel-ai/models/blob/main/squeezenet-burn/build.rs#L43

**Comment by mrvollger** [comment]
This was very helpful, thanks! The first thing I tried was `embed_states(true)`, but I couldn't get it to work because of errors like this:
```
  ERROR burn_import::logger: PANIC => panicked at /Users/mrvollger/.cargo/registry/src/index.crates.io-6f17d22bba15001f/burn-import-0.12.1/src/burn/graph.rs:157:17:
  Embedding states is not supported for NamedMpkFileRecorder.    
```
But your example led me to the fact that I needed to combine it with `.record_type(RecordType::Bincode)` to allow it to work. 

So this solved it for me! thanks so much!

For noobs like me, maybe consider adding to the error message that you can change to `RecordType::Bincode` to allow embedding of the states, but feel free to close. 

For others that might find this issue my change looked like going from this:
```
        ModelGen::new()
            .input(x) // Path to the ONNX model
            .out_dir("m6a_burn/") // Directory for the generated Rust source file (under target/)
            .run_from_script();
```
to this
```
        ModelGen::new()
            .input(x) // Path to the ONNX model
            .out_dir("m6a_burn/") // Directory for the generated Rust source file (under target/)
            .record_type(RecordType::Bincode)
            .embed_states(true)
            .run_from_script();
```

Thanks again.
