### ISSUE TITLE
JIT Cuda backend

### ISSUE THREAD

**Issue by nathanielsimard** [tracel-ai/burn#1525]
- [X] Fix JIT kernels that don't do bound checks when it's needed (pointer errors with cuda)
- [x] Fix memory corruption when running multiple tests concurently
- [x] Fix matmul kernels (maybe linked to shared memory)
- [x] Support fusion
- [x] Avoid build error when building the burn workspace and CUDA toolkit is not present (maybe use a `build.rs` file)

**Comment by wingertge** [comment]
I believe these are all done now
