### ISSUE TITLE
Upgrade to wgpu 0.19

### ISSUE THREAD

**Issue by astnmsn** [tracel-ai/burn#1546]
### Feature description

Upgrade to wgpu 0.19

### Feature motivation

I'm attempting to integrate into an existing rust project that uses `wgpu` and compiles to wasm.
The current version of `burn` (which depends on wgpu 0.18.0) is incompatible with my project which requires `wgpu` 0.19 because of a mismatch with `web_sys` feature `GpuComputePassTimestampWrite` because a newer version of web_sys has renamed this feature (GpuComputePassTimestampWrite -> GpuComputePassTimestampWrites). There is a similar issue in the `wgpu` project which can be found [here](https://github.com/gfx-rs/wgpu/issues/4776).

When performing a simple attempt to bump the `wgpu` dependency in `burn` to `0.19` and integrating it into my own build, I came across an issue with `WgpuServer` not being `Send`. The underlying issue seems to stem from the fact that `dyn wgpu::context::DynContext + 'static` is not send. 

I believe this is a change that occurred in wgpu in the 0.19 version. 

Note: With some very minor fixes and the `wgpu` bump to 0.19 - `burn` is able to build. But the integration into a project which targets wasm breaks.

**Comment by antimora** [comment]
We haven't upgraded because of https://github.com/tracel-ai/burn/issues/1222 regression bug. Actually we had to revert it.

**Comment by astnmsn** [comment]
Thanks for the quick response, and I had noticed that it was attempted. I thought it was also worth pointing out the other integration issues that I ran into when upgrading as they weren't detected by simply building `burn` on its own.

**Comment by syl20bnr** [comment]
I will look into this later today, we have another issue that tracks this: https://github.com/tracel-ai/burn/issues/1222

**Comment by syl20bnr** [comment]
Unfortunately the performance issue persists. Taking the `ag-news-train` example I get 32 iterations/sec with 0.18 and only 4 iterations/sec with 0.19.3.

You can try by executing the examples from main and then from the branch `wgpu-0.19.3`:

```
cargo run --example ag-news-train --release --features wgpu
```

**Comment by cryscan** [comment]
Does this issue still exist in WGPU v0.19.4? It seems okay for me now.

**Comment by nathanielsimard** [comment]
@cryscan Yup the issue seems to be fixed 🎉
