### ISSUE TITLE
The Burn book using outdated api?

### ISSUE THREAD

**Issue by tmheath** [tracel-ai/burn#1605]
The current version of the burn book calls CrossEntropyLoss::new with only a single argument where that method expects a second, being the device.  Also the init method the book previously prescribes requires the device to be passed where none is.  Is this intentional to be covered later in the guide (I skimmed it first but not in any great detail), or is this an actual problem (I tried just building but it would be useless to run until complete so I don't know if anything is wrong)?

The documentation is awesome btw

**Comment by laggui** [comment]
The Burn book is not versioned yet, so the hosted version is the last release version (v12.1).

We're thinking about hosting different versions, see issue #1325.

**Comment by tmheath** [comment]
I'm using 0.12.1 which is the one instructed via the example given first in the book, I didn't go about grabbing the latest or anything, just set things up to see if I could play around with it.

I'll go ahead and check that out still

**Comment by laggui** [comment]
> I'm using 0.12.1 which is the one instructed via the example given first in the book, I didn't go about grabbing the latest or anything, just set things up to see if I could play around with it.
> 
> I'll go ahead and check that out still

Oh you're right, there's still an issue with the book. That reference is outdated, will fix.

**Comment by tmheath** [comment]
Alright, side question...
The latest documentation found on crates.io is 0.12.1, the built book from the repo is 0.13.0, is that the dev version not yet available, or is there some kind of lag in getting crates.io/cargo updated (I can't use 0.13.0 which looks like it's the prelude one), I can go ahead and point it at the repo though, I don't know how all that works behind the scenes (I read about it before but memory).

**Comment by laggui** [comment]
0.13.0 is just the latest dev version not yet released! But the release is imminent.

You can keep working with 0.12.1 if you'd like, but we're about to release and there are some breaking changes so if you don't mind working with the git version at this time I'd probably suggest that.

**Comment by laggui** [comment]
Thanks for flagging the discrepancy btw! 🙂 Just made the change in the linked PR.
