### ISSUE TITLE
Update the book to implement Clone for MnistBatcher in example code.

### ISSUE THREAD

**Issue by tmheath** [tracel-ai/burn#1607]
Currently the structure in the examples in the built book define the structure as below.
```
pub struct MnistBatcher<B: Backend> {
    device: B::Device,
}
```
But one problem prevented a suceeding build, that being Clone was not implemented.
```
#[derive(Clone)]
pub struct MnistBatcher<B: Backend> {
    device: B::Device,
}
```
After making the change building works out of the box and can serve as a starting point.

**Comment by laggui** [comment]
Good catch!

We just changed that recently with #1575, looks like we forgot to reflect all of the changes in the book.

I'll fix that now. Thanks again! :)
