### ISSUE TITLE
[ndarray] General matmul broadcasting bug

### ISSUE THREAD

**Issue by laggui** [tracel-ai/burn#1646]
**Describe the bug**
Was double-checking our broadcasting support following #1499.

The general matmul implementation for the ndarray backend doesn't seem to compute the correct thing w.r.t. batch matrix broadcasting.

**To Reproduce**
```rust
use burn::{
    backend::{NdArray, Wgpu},
    tensor::Tensor,
};

fn main() {
    type B = NdArray;
    // type B = Wgpu;
    let device = Default::default();

    // (j x 1 x n x m) @ (1 x k x m x p) -> (j x k x n x p)
    let tensor_1 = Tensor::<B, 4>::ones([3, 1, 2, 4], &device);
    let tensor_2 = Tensor::<B, 4>::ones([1, 5, 4, 6], &device);
    let dims1 = tensor_1.dims();
    let dims2 = tensor_2.dims();
    let tensor_3 = tensor_1.matmul(tensor_2);
    println!("{:?} @ {:?} = {:?}", dims1, dims2, tensor_3.dims());
    // [3, 1, 2, 4] @ [1, 5, 4, 6] = [3, 5, 2, 6]
}
```
This code panics at `tensor_1.matmul(tensor_2)`:

```sh
thread '<unnamed>' panicked at /home/laggui/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ndarray-0.15.6/src/dimension/mod.rs:361:5:
collapse_axis: Index 3 must be less than axis length 3 for array with shape [3, 2, 4]
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at /home/laggui/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ndarray-0.15.6/src/dimension/mod.rs:361:5:
collapse_axis: Index 4 must be less than axis length 3 for array with shape [3, 2, 4]
```

**Expected behavior**
The matmul should result in an output with shape `[3, 5, 2, 6]`. Works on wgpu.

**Comment by lancelet** [comment]
I took a quick look at this. `Wpu` seems to behave the same as [numpy.matmul](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html). I added this test to `burn-tensor/src/test/ops/matmul.rs`, which passes with `Wgpu`, but fails with `ndarray` (values match what `numpy.matmul` produces):
```rust
    #[test]
    fn test_matmul_broadcast_4d() {
        let device = Default::default();
        // [2, 1, 2, 2]
        let tensor_1 = TestTensor::from_floats(
            [[[[1.0, 7.0], [2.0, 3.0]]], [[[2.0, 5.0], [6.0, 3.0]]]],
            &device,
        );
        // [1, 2, 2, 2]
        let tensor_2 = TestTensor::from_floats(
            [[[[9.0, 8.0], [1.0, 4.0]], [[2.0, 7.0], [3.0, 5.0]]]],
            &device,
        );

        // [2, 1, 2, 2] @ [1, 2, 2, 2] -> [2, 2, 2, 2]
        let tensor_3 = tensor_1.matmul(tensor_2);

        assert_eq!(
            tensor_3.into_data(),
            Data::from([
                [[[16.0, 36.0], [21.0, 28.0]], [[23.0, 42.0], [13.0, 29.0]]],
                [[[23.0, 36.0], [57.0, 60.0]], [[19.0, 39.0], [21.0, 57.0]]]
            ])
        )
    }
```

The logic in `burn-ndarray/src/ops/matmul.rs` seems to require an overhaul. There seem to be some assumptions there about how flattening can simplify the multiplication that won't work properly with broadcasting.

I'll keep looking (just posting the test above in case I run out of time).

**Comment by lancelet** [comment]
OK; PR raised here: https://github.com/tracel-ai/burn/pull/1679

I'm completely new to `burn`, so please let me know what extra tests, examples, docs, etc. should be added.

I saw a mention in another PR of improving the docs for `matmul`. Should I put that into this PR as well?

**Comment by laggui** [comment]
Hi @lancelet, thanks for looking into this! 🙂 I'll take a quick look at your PR for this issue specifically.

We do want to improve our documentation regarding the general broadcasting semantics in burn, and also matmul. If you want to take a stab at it you could open another PR!
