### ISSUE TITLE
Flaky test: subsequent_calls_give_different_tensors

### ISSUE THREAD

**Issue by louisfd** [tracel-ai/burn#1648]
Our jit test `subsequent_calls_give_different_tensors`  whether for bernoulli, normal and uniform, fails from time to time. 
This test is tagged as "serial" which means it is not supposed to run in parallel to other tests. 

This is because it sets the seed to 0, then computes twice the same thing, which should have different outcomes because the RNG state changes. Of course if another test puts the seed back to zero between the two calls it's going to be the same and fail. 

Because the tests pass most of the times but can fail, it makes me doubt that "serial" works as expected.

**Comment by nathanielsimard** [comment]
Other tests can be executed at the same time, only the ones in the same file tagged as serial will be tested in squence I suspect.

**Comment by louisfd** [comment]
I think you're right. 
I suggest we delete those three tests as they don't add much value, they just make sure that the jit prng changes the rng state
