### ISSUE TITLE
If the batch size is 1, testing LSTM on the Wgpu backend will fail

### ISSUE THREAD

**Issue by wcshds** [tracel-ai/burn#1656]
**Describe the bug**
If the batch size is 1, testing LSTM on the Wgpu backend will fail.

**To Reproduce**
1. Change the batch size of the input in `test_batched_forward_pass` of LSTM from 8 to 1.
https://github.com/tracel-ai/burn/blob/2a721a9d0c73e36fabd9c9cf337bd3ca4d8d1acc/crates/burn-core/src/nn/rnn/lstm.rs#L319-L330

to
```rust
    #[test]
    fn test_batched_forward_pass() {
        let device = Default::default();
        let lstm = LstmConfig::new(64, 1024, true).init(&device);
        let batched_input =
            Tensor::<TestBackend, 3>::random([1, 10, 64], Distribution::Default, &device);

        let (cell_state, hidden_state) = lstm.forward(batched_input, None);

        assert_eq!(cell_state.shape().dims, [1, 10, 1024]);
        assert_eq!(hidden_state.shape().dims, [1, 10, 1024]);
    }
```

2. Run the command: `cargo test -p burn-core --features test-wgpu`. The test will fail.

**Comment by antimora** [comment]
CC @louisfd @nathanielsimard

**Comment by nathanielsimard** [comment]
@wcshds I can't reproduce it on my computer (I'm on Linux/Vulkan). I think there are corruption issues with wgpu on the Metal backend. Are you on a Mac? We are investigating the issues; it may be linked to how we build the compute pass in wgpu where we assume each pipeline is executed in the same order as registered. Still investigating.

**Comment by wcshds** [comment]
@nathanielsimard I am using Ubuntu22.04/Vulkan under WSL.

![image](https://github.com/tracel-ai/burn/assets/8537285/55b6552a-7992-4db3-8723-233a74522e9a)


![image](https://github.com/tracel-ai/burn/assets/8537285/72ed8ffc-483b-4976-84d1-a9be1d20d44a)

**Comment by wcshds** [comment]
@nathanielsimard The bug still exists on main. But #1659 seems to resolve this problem on my device.

**Comment by nathanielsimard** [comment]
@wcshds the PR #1659 just disable inplace operations with fusion, the if will always output false.

**Comment by nathanielsimard** [comment]
@wcshds Maybe there is a problem with array visibility caused by the dynamic use of fused inplace operation. The problem is only present with a batch size of 1 since the shape of the tensor is not compatible with another operation for fusion, whereas with a batch dimension it is.
