### ISSUE TITLE
redirection link in the "Importing Models"

### ISSUE THREAD

**Issue by Paulo-21** [tracel-ai/burn#1671]
Hello,
it's seem that in the [Importing Models](https://burn.dev/book/import/index.html#importing-models) page of the burn book, the link to ONNX and Pytorch redirect to burn.dev.
It should be to the section related in the book isn't it ?
Like ONNX link to [Import ONNX Model](https://burn.dev/book/import/onnx-model.html#import-onnx-model)
and Pytorch to [PyTorch Model](https://burn.dev/book/import/pytorch-model.html#pytorch-model)

Best Regards

**Comment by laggui** [comment]
Thanks for flagging! Just submitted a PR that should fix this 🙂

**Comment by laggui** [comment]
Yeah this one has been fixed in #1651
