### ISSUE TITLE
Replace unwrap with expect.

### ISSUE THREAD

**Issue by nathanielsimard** [Tracel-AI/burn#196]
Replace `unwrap` with clear `expect` explaining why it's OK to ignore a result.

**Comment by antimora** [comment]
I am closing this as too open ended. We should be more aggresive in our code review to disallow such lines.

**Comment by Luni-4** [comment]
@antimora 

I would leave this issue open as a reminder for the current code which stil uses `unwrap` instead of expected. We can label this issue as `good first issue`, perhaps some contributor can help us with this task

**Comment by antimora** [comment]
> @antimora
> 
> I would leave this issue open as a reminder for the current code which stil uses `unwrap` instead of `expect`. We can label this issue as `good first issue`, perhaps some contributors are willing to help us with this task

It's way too open ended. We should have something more precise. We can have a bunch of issues like this laying around without specific action items.
