### ISSUE TITLE
Prevent users from creating 0-d tensors

### ISSUE THREAD

**Issue by saihaze** [tracel-ai/burn#2002]
### Feature description

Panic when a user's trying to create an 0-d tensor.

### Feature motivation

I am a beginner and try to create a scalar. I thought it should be 0-d (with shape []). However, this doesn't really work. I spent a lot of time debugging due to lack of hints. I know that I am stupid, but panicking at creating 0-d tensors will help.

### Suggest a Solution
In Tensor's constructors:
```rust
assert!(D != 0)
```

**Comment by antimora** [comment]
Linking #1689

**Comment by antimora** [comment]
Yes, I agree we should prevent 0d tensors and instead create Scalar type outlined in #1689.
