### ISSUE TITLE
Enable dataset creation from a Polars Dataframe

### ISSUE THREAD

**Issue by ragyabraham** [tracel-ai/burn#2015]
### Feature description

Provide a native method for creating a Burn dataset from a Polars dataframe
### Feature motivation

Polars is quickly becoming the pandas of the Rust ecosystem so it makes sense to build support given data frames are the mainstream abstraction for data in ML

**Comment by antimora** [comment]
It wouldn't too difficult to wire up the two. What specifically you'd like to see in the API?

**Comment by ragyabraham** [comment]
I agree. I have a crude implementation of this myself, but I think it makes sense to have this functionally built into Burn, as it would greatly help its value addition. We can start to build a comprehensive ecosystem in Rust that plays well together, much like Python.

From an API perspective, I think we can start with something simple. `InMemDataset::from_dataframe()` would be the simplest place to start.

Maybe something along these lines?? What do you think??

```rust
   pub fn from_dataframe(df: DataFrame<I>) -> Result<Self, std::io::Error>{
        ...
        Ok(dataset)
    }
```

**Comment by ragyabraham** [comment]
Also, I would be happy to contribute to this ticket. If you wouldn't mind helping me navigate the library, it would be a nice, gentle way for me to get introduced to the inner workings of Burn.

**Comment by antimora** [comment]
> Also, I would be happy to contribute to this ticket. If you wouldn't mind helping me navigate the library, it would be a nice, gentle way for me to get introduced to the inner workings of Burn.

Sure. You can join discord for a faster response time. You are welcome to submit a PR and solicit some feedback (in draft version). We contributor book as well. 

I would start looking into the dataset types we have, in particular SqliteDataset and see what common patterns you can use in your API. 

Regarding your suggestion: `InMemDataset::from_dataframe()`. This seems hard coupling the two. Instead, I would create dataframe dataset wrapper. InMemDataset would be able to take in another dataset and consume it, thus it would be loosely coupled.
