### ISSUE TITLE
burn-import: Unsupported node conversion Split

### ISSUE THREAD

**Issue by KhaledHosseini** [tracel-ai/burn#2038]
**Describe the bug**

When I try to convert an onnx file, the following error arises:
ERROR burn_import::logger: PANIC => panicked at ...\burn-import-0.13.2\src\onnx\to_burn.rs:270:22:
  Unsupported node conversion Split

**Comment by laggui** [comment]
We don't currently support the `Split` operator, but we have `tensor.chunk` on the Burn side which could be equivalent to an even split (part of the `Split` spec).

**Comment by laggui** [comment]
Closing in favor of #2440
