### ISSUE TITLE
Indexing a tensor of dimension D and get a tensor of dimension D-1.

### ISSUE THREAD

**Issue by KhaledHosseini** [tracel-ai/burn#2066]
### Feature description
suppose we have a 5D tensor, with shape [3,4,5,6,7]. Then indexing the tensor[index] gives me a 4D tensor with shape [4,5,6,7].

**Comment by antimora** [comment]
It would be slice and unqueez operation.

**Comment by KhaledHosseini** [comment]
> It would be slice and unqueez operation.

Thank you for your quick reply. Can you give me an example, please?

**Comment by nathanielsimard** [comment]
Since const expressions aren't supported in Rust yet, all indexing operations are keeping the same rank (similar to how Python does it using keep_dim=True). When const expressions land on stable, we could consider having another API where the rank is modified based on the indexing operation.
