### ISSUE TITLE
Guide example does not compile due to cubecl update

### ISSUE THREAD

**Issue by shinglyu** [tracel-ai/burn#2082]
**Describe the bug**

The examples/guide does not compile because of an updated parameter type in the cubecl dependency. 

**To Reproduce**
1. `cd examples/guide`
2. `cargo run --bin train --release`

**Expected behavior**
The example compiles and runs.

**Screenshots**
Got multiple compile errors like this:
error[E0308]: mismatched types
  --> crates/burn-jit/src/fusion/elemwise/kernel.rs:98:84
   |
98 |                 let cube_count = calculate_cube_count_elemwise(num_elems / factor, self.cube_dim);
   |                                  -----------------------------                     ^^^^^^^^^^^^^ expected `usize`, found `CubeDim`
   |                                  |
   |                                  arguments to this function are incorrect
   |
note: function defined here
  --> /home/sagemaker-user/.cargo/git/checkouts/cubecl-aa41a28b39b598f9/2b95a9e/crates/cubecl-core/src/lib.rs:55:8
   |
55 | pub fn calculate_cube_count_elemwise<S: ComputeServer>(
   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.4 LTS (in SageMaker Studio CodeEditor)
 - Browser: N/A
 - Version: N/A

**Additional context**
cubecl was updated 5 days ago: https://github.com/tracel-ai/cubecl/commit/367bd4c38ae16bb4660a60399bbb4a4c95e02755 with this breaking change. But a `cargo update cubecl` does not seem to fix it.

**Comment by shinglyu** [comment]
Root cause: https://github.com/tracel-ai/cubecl/issues/44

**Comment by nathanielsimard** [comment]
We fixed the problem by setting the correct version of burn: https://github.com/tracel-ai/burn/commit/eb9e8228322dc0a4e28da09bc4b483de401ab1e8

Since CubeCL is early we won't create a release for every breaking changes, only when publishing Burn, so that both project can evolve together.
