### ISSUE TITLE
ONNX import issue: `index out of bounds` in `pad_config()` due to `node.input` only having len of `2`

### ISSUE THREAD

**Issue by SimonBrandner** [tracel-ai/burn#2111]
```
ERROR burn_import::logger: PANIC => panicked at /home/simon/.cargo/git/checkouts/burn-178c6829f420dae1/f7639bd/crates/burn-import/src/onnx/op_configuration.rs:802:27:
index out of bounds: the len is 2 but the index is 2
```

Link to model: https://drive.google.com/file/d/1E6fNKzGE3_JhEokgqqHDqJxwqw3UUku9/view?usp=drive_link

**Comment by antimora** [comment]
Yes, it seems all ops in the ONNX file should be supported.

**Comment by antimora** [comment]
CC @mepatrick73 it's a good one to take to fix a bug.

**Comment by mepatrick73** [comment]
I'll get on it!

**Comment by mepatrick73** [comment]
This problem is now fixed, there are more issues with the model. Specifically the avgpool operation uses ceilling mode which we currently do not support. If you could make a new issue, that would be wonderful. 

Anyhow, I'll close this issue as it is now fixed.

**Comment by SimonBrandner** [comment]
Thanks @mepatrick73!
