### ISSUE TITLE
Tensor::Interpolate function like torch.nn.functional.interpolate

### ISSUE THREAD

**Issue by KhaledHosseini** [tracel-ai/burn#2126]
### Feature description
I am about to convert a Pytorch model to burn. Still, I could not find a way to implement an interpolate function like [torch.nn.functional.interpolate](https://pytorch.org/docs/stable/generated/torch.nn.functional.interpolate.html) using existing burn functions. I would appreciate any information or guidance you could give me. for the moment, my use case is a double upscale using nearest neighbor mode.

**Comment by laggui** [comment]
Actually we have `burn::tensor::module::interpolate`, but I now realize the module ops are not documented in the burn book.

Check out how it's [used in YOLOX in the models repo](https://github.com/tracel-ai/models/blob/main/yolox-burn/src/model/pafpn.rs#L38-L45).

**Comment by KhaledHosseini** [comment]
> Actually we have `burn::tensor::module::interpolate`, but I now realize the module ops are not documented in the burn book.
> 
> Check out how it's [used in YOLOX in the models repo](https://github.com/tracel-ai/models/blob/main/yolox-burn/src/model/pafpn.rs#L38-L45).

You saved my life bro!

**Comment by laggui** [comment]
Ah great, so the actual modules are documented now! Good 🙂
