### ISSUE TITLE
Img links of  burn/examples /onnx-inference are missing.

### ISSUE THREAD

**Issue by tiruka** [tracel-ai/burn#2133]
**Describe the bug**
The image link of https://github.com/tracel-ai/burn/tree/main/examples/onnx-inference#usage and  https://github.com/tracel-ai/burn/blob/main/examples/onnx-inference/src/bin/mnist_inference.rs#L64 are missing.

**To Reproduce**
https://github.com/tracel-ai/burn/tree/main/examples/onnx-inference#usage
```
https://datasets-server.huggingface.co/assets/mnist/--/mnist/test/15/image/image.jpg
```
When you open the above link, you can see it is missing as the below screen shot section.

**Expected behavior**
We can find the correct image

**Screenshots**
<img width="935" alt="image" src="https://github.com/user-attachments/assets/e5c3cf44-5ceb-4a90-bc72-aef71ccc2640">

**Comment by antimora** [comment]
Completed via #2134
