### ISSUE TITLE
Rewrite pooling operations from CPA to CubeCL in Burn-JIT

### ISSUE THREAD

**Issue by mepatrick73** [tracel-ai/burn#2140]
### Feature description
Rewrite the pooling operations from cube pseudo assembly to CubeCL

### Feature motivation
#2132 requires ceilling mode to be supported, but this requires rewriting code that currently use cpa! macros. This is currently not an easy task, and we might aswell rewrite in CubeCL.

**Comment by booti386** [comment]
Working on it!

**Comment by nathanielsimard** [comment]
From our testing, those are the only operations that cause problems with the new cuda-jit backend 😬

**Comment by laggui** [comment]
#2356 #2455 🔥
