### ISSUE TITLE
xtask default args are not used

### ISSUE THREAD

**Issue by tiruka** [tracel-ai/burn#2162]
**Describe the bug**

Some `xtask` commands without args cannot work well.

**To Reproduce**

```
% cargo xtask dependencies
   Compiling xtask v0.5.0 (/Users/tiruka/Desktop/oss-fork/burn/xtask)
    Finished `dev` profile [optimized] target(s) in 1.81s
     Running `target/debug/xtask dependencies`
error: the following required arguments were not provided:
  <DEPENDENCY_CHECK>

Usage: xtask dependencies <DEPENDENCY_CHECK>

```

```
% cargo xtask vulnerabilities
    Finished `dev` profile [optimized] target(s) in 0.19s
     Running `target/debug/xtask vulnerabilities`
error: the following required arguments were not provided:
  <VULNERABILITY_CHECK>

Usage: xtask vulnerabilities <VULNERABILITY_CHECK>

For more information, try '--help'.
```

**Expected behavior**

Judging from code like [dependencies.rs enum default value](https://github.com/tiruka/burn/blob/feat/modify-examples-using-mnist-model/xtask/src/dependencies.rs#L17), All will be used when executing the command without args.

**Comment by nathanielsimard** [comment]
@syl20bnr is reworking how xtask is working, see #2063

**Comment by tiruka** [comment]
@nathanielsimard 
Could you elaborate it?
Do you mean I should change target branch or withdraw my PR?

I am not sure ongoing status and detailed changes.
The way I see it, if it takes time reworking refactoring, the fix may be merged to prevent any confusions of users even though it will be discarded soon.

**Comment by tiruka** [comment]
Okay, anyway it looks better to wait and see now.

**Comment by syl20bnr** [comment]
Hi @tiruka I replied to you on the other issue about machete. You can start looking at our [tracel-xtask repo](https://github.com/tracel-ai/xtask) to get familiar with it, we are about to release it very soon and I suggest to wait for the release before starting to contribute to it.

I fixed this bug in  https://github.com/tracel-ai/xtask/commit/4ef9b34989a0660ebd81dbc5d8e13a97e94d5ca2 so we can close this issue.

**Comment by tiruka** [comment]
Sure, thank you for fixing it.
