### ISSUE TITLE
`mnist-inference-web` wgpu matmul returns all zeros

### ISSUE THREAD

**Issue by laggui** [tracel-ai/burn#2178]
**Describe the bug**
The wgpu matmul implementation returns all zeros when running in the browser.

Also reported by a discord user: https://discord.com/channels/1038839012602941528/1059209073784008835/1273995743790628876

**To Reproduce**
Run the `mnist-inference-web` example built for wgpu.

The scores returned are always the same for all digits.

![image](https://github.com/user-attachments/assets/816b0e98-2588-4df4-afee-1ea66ff3b2c7)

Upon further debugging, the `fc1` layer always returns zeros because of the matmul issue (tiling2d implementation w/ cube). Note that using the simple matrix multiply works (and cmma is not available in this case).

**Expected behavior**
The results from the matmul should not be zero, and thus the scores correct.

**Comment by nathanielsimard** [comment]
This should fix it: https://github.com/tracel-ai/cubecl/pull/81

**Comment by laggui** [comment]
Just tested, this was fixed when updating to the latest cubecl version to include the fix in #2181
