### ISSUE TITLE
burn-import getting error `Gather: indices tensor rank above 1 not supported`

### ISSUE THREAD

**Issue by catethos** [tracel-ai/burn#2192]
**Describe the bug**
When I am trying to import this onnx model: [onnx/model.onnx · Xenova/paraphrase-multilingual-mpnet-base-v2 at m...](https://huggingface.co/Xenova/paraphrase-multilingual-mpnet-base-v2/blob/main/onnx/model.onnx), I am getting this error `Gather: indices tensor rank above 1 not supported`
 
**To Reproduce**
1. download the onnx file from the hf hub
2. run the build script to convert

**Expected behavior**
the conversion should work without error

**Comment by laggui** [comment]
@alteredoxide I know you were working on a PR to resolve that issue, just wanted to let you know we can track the progress here.

**Comment by alteredoxide** [comment]
@laggui Thanks! My attention has been elsewhere for the past couple days, but the last round of tests after in-lining the gather code all passed. I just want to review everything once before my final commit+submit. I'll probably get around to that this Saturday.

**Comment by laggui** [comment]
> @laggui Thanks! My attention has been elsewhere for the past couple days, but the last round of tests after in-lining the gather code all passed. I just want to review everything once before my final commit+submit. I'll probably get around to that this Saturday. 

No rush! Be sure to request my review so I don't miss your PR when you're ready :)

**Comment by alteredoxide** [comment]
@laggui I have created the PR here: #2199 but I don't have the ability to specifically add/request your review.

**Comment by laggui** [comment]
> @laggui I have created the PR here: #2199 but I don't have the ability to specifically add/request your review.

Ah whoops forgot about the contributor restrictions 😅 thank you, will take a look at this tomorrow!

**Comment by alteredoxide** [comment]
Haha no worries

**Comment by laggui** [comment]
Completed in #2199
