### ISSUE TITLE
Type Annotation Needed Error in .map(|data| Tensor::<B, 2>::from_data(data.convert(), &self.device)) in Burn 0.14

### ISSUE THREAD

**Issue by sascharo** [tracel-ai/burn#2210]
I'm following the "Basic Workflow: From Training to Inference" in "The Burn Book" with Burn 0.14, specifically on the [Data section](https://burn.dev/book/basic-workflow/data.html). When trying to run the line `.map(|data| Tensor::<B, 2>::from_data(data.convert(), &self.device))`, I encounter the following error:
```
error[E0283]: type annotations needed
.map(|data| Tensor::<B, 2>::from_data(data.convert(), &self.device))
^^^^^^^ cannot infer type of the type parameter `E` declared on the method `convert`
note: cannot satisfy `_: Element`
help: the following types implement trait `Element`:
              bf16
              bool
              burn::tensor::f16
              f32
              f64
              i16
              i32
              i64
            and 4 others
note: required by a bound in `TensorData::convert`
```
It seems like the type inference for Element in the `convert()` method is failing. Could you please provide guidance on how to resolve this issue or what specific type annotation might be required?

**Comment by laggui** [comment]
Good catch! Looks like we didn't update the book accordingly, I'll fix this.

In the meantime, take a look at how it's done in the [accompanying code from the examples](https://github.com/tracel-ai/burn/blob/main/examples/guide/src/data.rs#L28):

```rust
.map(|data| Tensor::<B, 2>::from_data(data.convert::<B::FloatElem>(), &self.device))
```

**Comment by sascharo** [comment]
Thank you for the quick response! I tried the fix, and it worked perfectly.
