### ISSUE TITLE
Detection issue with heterogenous cards

### ISSUE THREAD

**Issue by Globibluk** [tracel-ai/burn#2242]
**Describe the bug**
Burn only lists one card with WGPU when both AMD and NVIDIA cards are installed.
7800XT and 2080Ti

**To Reproduce**
Modify Mnist example with WGPU to use card 1 instead of card 0.
Burn stops stating only one card is detected (the AMD one in my case).

**Expected behavior**
Burn starts the example using the NVIDIA card.

**Desktop**
 - OS: Ubuntu 22.04
 - Browser: Not relevant
 - Version: Latest git: [59d41bd](https://github.com/tracel-ai/burn/commit/59d41bd4b2c2883f14d5aa763e5b40d4b411c9cf)

**Additional context**
Have two cards installed in order to perform tests easily.
Running the NVIDIA card alone works as expected.

**Comment by laggui** [comment]
Sorry for the late response, didn't notice this issue.

Just to make sure I understand this correctly, your AMD card is not being detected for WGPU?

Do you know if it is detected by vulkan? Maybe something is missing for your AMD card 🤔

**Comment by Globibluk** [comment]
No problem. In fact only the AMD card is detected. The NVIDIA one is not.

**Comment by laggui** [comment]
> Burn stops stating only one card is detected (the AMD one in my case).

Whoops, I read that the other way around 😅 Thanks for clarifying.

You said you modified the example to specify which device to use. Do you have the code example? And perhaps the full error trace could also help identify the issue.

**Comment by Globibluk** [comment]
I run the mnist example with only a single tweak:

line 47: `let device = WgpuDevice::DiscreteGPU(1);`

The related error is : "No Discrete device found, adapters [...]"
It only lists the AMD one.

**Comment by laggui** [comment]
Ahh ok and in the adapters listed in the error message the CUDA device is not listed.

When you say you can use the card with cuda dedicated code, do you mean that it works with Burn using something else?

If not, it could be that vulkan does not detect the device. You could check with vulkan tools (e.g., vkinfo or vkcube) in that case to see if it is a wgpu issue or vulkan issue.

**Comment by Globibluk** [comment]
Thanks for your response. I checked and it seems that for some reason the nvidia icd file was missing.
Everything works properly now.
Thanks a lot!
