### ISSUE TITLE
mask_where function fails with NaN values in ndarray backend

### ISSUE THREAD

**Issue by nusu-github** [tracel-ai/burn#2253]
## Describe the bug

`ndarray` backend fails to correctly apply the `mask_where` function when working with tensors that contain `NaN` values. Specifically, when applying `mask_where` to a tensor created using `zeros_like()` with `NaN` values, the result is all `NaN` values instead of the expected masked values. This issue does not occur with other backends like `wgpu`.

## To Reproduce

1. Define a tensor with the `ndarray` backend.
2. Create a mask from a comparison operation on the tensor.
3. Apply `zeros_like()` to the tensor, add `NaN` values, and use `mask_where` with another tensor to fill masked elements.
4. Observe that the result contains `NaN` values where masked elements should have been replaced.

```rust
use burn::{backend::NdArray, tensor::{Float, Tensor}};

fn main() {
    type B = NdArray;

    let device = burn::backend::ndarray::NdArrayDevice::default();

    let x = Tensor::<B, 2, Float>::from_floats([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6], [0.7, 0.8, 0.9]], &device);
    let y = Tensor::<B, 2, Float>::from_floats([[0.9, 0.8, 0.7], [0.6, 0.5, 0.4], [0.3, 0.2, 0.1]], &device);
    let mask = x.clone().lower_equal_elem(0.5);

    let z = x.zeros_like().add_scalar(f32::NAN);
    let z = z.mask_where(mask, y);

    println!("{}", z);
}
```

## Expected behavior

The `mask_where` function should apply correctly, replacing the elements where the mask is true with values from the second tensor. The expected result should look like this, as seen with the `wgpu` backend:

```
Tensor {
  data:
  [[0.9, 0.8, 0.7],
   [0.6, 0.5, NaN],
   [NaN, NaN, NaN]],
  shape: [3, 3],
  device: BestAvailable,
  backend: "fusion<jit<wgpu>>",
  kind: "Float",
  dtype: "f32",
}
```

## Environment

**Desktop:**

- OS: Debian 12
- Backend: `ndarray`
- Version: 0.14.0

**Comment by laggui** [comment]
Thanks for flagging! I just opened a PR that fixes the issue.
