### ISSUE TITLE
Add the ability to access the underlying wgpu::Buffer of a Tensor when using the Wgpu backend. 

### ISSUE THREAD

**Issue by amanshenoy** [tracel-ai/burn#2274]
When we use burn with a Wgpu backend, the underlying storage of the Tensors are wgpu::Buffers.  It would be really helpful for a lot of use cases if we could directly have access to the wgpu::Buffer. 

This is particularly useful when working with a wgpu based renderer. For example in my use case, I am using Burn to compute the vertices and other vertex attributes of a mesh which I want to then pass to my renderer. Currently I would have to convert the burn Tensor to CPU and then create a new wgpu::Buffer using this. 

For such applications it would be very helpful to have direct access to the wgpu::Buffer, which would allow us to do a buffer to buffer copy (while doing init_existing_device). 

The ability to do this might already exist but I was not able to find anything in the documentation regarding this.

**Comment by ArthurBrussee** [comment]
You can already do this! Something like:

```rust
// Get underlying jit tensor.
let jit_tensor = my_tensor.into_primitive().tensor();

// Get the 'resource' from the client
let resource = jit_tensor.client.get_resource(jit_tensor.handle.clone().binding());
// Which has the wgpu buffer.
let buffer = resource.buffer;
// But do note it only uses a part of the buffer, see offset + size.
let offset = resource.offset;
// Nb: For the buffer to be in a consistent state first flush all pending work if needed.
img.client.sync(burn::tensor::backend::SyncType::Flush);
```

**Comment by AsherJingkongChen** [comment]
Is it closable now?
