### ISSUE TITLE
How to use audio data for training?

### ISSUE THREAD

**Issue by huahuadeliaoliao** [tracel-ai/burn#2294]
I'm new to Burn and would like to ask if Burn has any features similar to PyTorch's `torchaudio`. If not, can I use decoding tools like `GStreamer` to decode audio files, convert them into tensors, and then use Burn for training?

**Comment by antimora** [comment]
We do not have the full audio tool support. You can bring in your own libraries. There is a audio feature you can enable for burn-dataset to play with speech commands.

**Comment by huahuadeliaoliao** [comment]
Thanks for your reply, I'll try to make it work if possible
