### ISSUE TITLE
multi threads support

### ISSUE THREAD

**Issue by wangjiawen2013** [tracel-ai/burn#2345]
Hi,
I tried the guide example and found that only one cpu was used. We have 128 cpus in our server, how to train the model using multi-threads ?

**Comment by laggui** [comment]
Have you modified the guide to use a different backend for CPU?

Otherwise, we have `ndarray` and `tch` which support intra-op parallelization for CPU.

**Comment by wangjiawen2013** [comment]
Yes, I used ndarray backend, but I don't know how to support parallelization.

**Comment by laggui** [comment]
Well first, I think for better CPU performance you're probably better off using `tch` which leverages MKL. Additionally, the operations would be parallelized by libtorch to use all available cores on your machine. So technically if your batch size is maxed out, this should leverage as much of the cores as possible I believe.

Does that answer your question? Or are you speaking of another form of parallelism?

**Comment by wangjiawen2013** [comment]
Yes, I'll try, thanks!
