### ISSUE TITLE
MseLoss forward input

### ISSUE THREAD

**Issue by wangjiawen2013** [tracel-ai/burn#2371]
Hi,
The `MseLoss::new().forward` requires input and targets have the same shape:
![image](https://github.com/user-attachments/assets/25443eaf-da59-4deb-8fcf-6e1d96cfb28f)
But in the simple regression example, the shapes are different, and I calculated the MseLoss by hand, the results are also different with the result generated by burn.
![image](https://github.com/user-attachments/assets/76ff6e4d-d141-442b-8c15-a807cb3825fd)
So I doubt that the calculation used a wrong MseLoss formula.

Then I performed an experiment:
```rust
use burn::tensor::Tensor;
use burn::backend::{Autodiff, NdArray};
use burn::prelude::*;
use burn::{
    nn::{
        loss::{MseLoss, Reduction::Mean},
        Linear, LinearConfig, Relu,
    },
    prelude::*,
    tensor::backend::AutodiffBackend,
    train::{RegressionOutput, TrainOutput, TrainStep, ValidStep},
};

type MyBackend = NdArray<f32, i8>;
type AutodiffBackend = Autodiff<MyBackend>;
let device = burn::backend::ndarray::NdArrayDevice::default();
let x = Tensor::<MyBackend, 2>::from_data([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], &device);
let targets = Tensor::<MyBackend, 1>::from_data([1.0, 2.0], &device);
let input_layer: Linear<MyBackend> = LinearConfig::new(3, 1)
    .with_bias(true)
    .init(&device);
let x = x.detach();
let x: Tensor<MyBackend, 2> = input_layer.forward(x);
let targets: Tensor<MyBackend, 2> = targets.unsqueeze();
let loss: Tensor<MyBackend, 1> = MseLoss::new().forward(x.clone(), targets, Mean);
```
I can run the above code, though input and targets are of different size. So it seems that input and targets don't have to have the same shape. 
Besides, I doubt that `let targets: Tensor<MyBackend, 2> = targets.unsqueeze();` is a mistake. Is it should be `let targets: Tensor::<MyBackend, 2> = targets.unsqueeze_dim(1);` ?

**Comment by laggui** [comment]
Fixed by #2379
