### ISSUE TITLE
Breaking change, Raspberry Pi Pico example will not compile

### ISSUE THREAD

**Issue by BjornTheProgrammer** [tracel-ai/burn#2389]
**Describe the bug**
With the latest commit of "Merge `cubecl-wgpu` and `cubecl-wgpu-spirv`", there has been a breaking change. The Raspberry Pi Pico example will not compile.

I know where the issue originates, see below.

**To Reproduce**
 1. Run `rustup target install thumbv6m-none-eabi`
 2. Cd into `burn/examples/raspberry-pi-pico`
 3. Run `cargo build`

```
   Compiling burn-ndarray v0.15.0 (/Users/bjorn/Documents/GitHub/burn/crates/burn-ndarray)
error: you may not enable `critical-section` feature and `portable_atomic_unsafe_assume_single_core` cfg (`unsafe-assume-single-core` feature) at the same time
   --> /Users/bjorn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/portable-atomic-1.9.0/src/lib.rs:413:1
    |
413 | / compile_error!(
414 | |     "you may not enable `critical-section` feature and `portable_atom...
415 | | );
    | |_^
```

**Expected behavior**
Successful build with no errors.

**Desktop**
 - OS: MacOS 14.6.1 (23G93)
 - Browser: None

**Additional context**
I coincidentally ran upon this issue, when trying to determine the binary size of the smaller model, and tried to compile using the raspberry-pi-pico example. It did not work.

As such, upon looking into it, it was only the last three commits that this example did not compile correctly. I realized that cubecl had been updated, and found the feature flag `unsafe-assume-single-core` had been enabled in [#176](https://github.com/tracel-ai/cubecl/pull/176).

This is what is causing the error.

I can submit a pull request to `cubecl` to fix this issue, additionally, it seems like there should be an xtask test for compiling the Raspberry Pi Pico example, or something similar. I can also submit a pull request if needed. However, I would like some input on how you would want full integration build tests to be done.

This should be fixed before any minor release.

**Comment by laggui** [comment]
It might be wise to have some tests for this use case, but for the short term we can start by simply fixing what was broken.

If you want to take a stab at it as you suggest, by all means go ahead 🙂

**Comment by BjornTheProgrammer** [comment]
I submitted a pull request to Cubecl to fix the issue! Just need that merged before updating the revision.

**Comment by laggui** [comment]
Fixed thanks to your PR in cubecl🙏 

I'll open a separate issue regarding the tests to avoid regressions in the future since this example is not currently covered
