### ISSUE TITLE
Upgrade Ratatui to the latest version

### ISSUE THREAD

**Issue by orhun** [tracel-ai/burn#2420]
### Feature description

As of now, the terminal dashboard depends on a bit of an old version of `ratatui`:

https://github.com/tracel-ai/burn/blob/c984429cbbac2c43b3ac4111e5861198e4ebded4/Cargo.toml#L99-L101

The latest version is [`v0.29.0`](https://github.com/ratatui/ratatui/releases/tag/v0.29.0)

### Feature motivation

Better terminal experience with less bugs :)

### (Optional) Suggest a Solution

The list of breaking changes are [here](https://github.com/ratatui/ratatui/blob/main/BREAKING-CHANGES.md). The upgrade should be smooth :) 

If you want to use any of the new features, there are release highlights which go into the details of each major feature:

- https://ratatui.rs/highlights/v027/
- https://ratatui.rs/highlights/v028/
- https://ratatui.rs/highlights/v029

**Comment by laggui** [comment]
Thanks for the detailed changes! Was pretty smooth indeed 😄
