### ISSUE TITLE
performance regression in training FSRS

### ISSUE THREAD

**Issue by L-M-Sherlock** [tracel-ai/burn#2438]
**Describe the bug**

After upgrading from 0.13.2 to 0.15.0, the training slows down 20%.

**To Reproduce**

1. git clone https://github.com/open-spaced-repetition/fsrs-rs
2. run this test: cargo test --release -- training::tests::training --nocapture
3. git checkout update-burn-to-v0.15.0
4. run the test again

**Expected behavior**

The test should be finished in the same time.

**Additional context**

- https://github.com/open-spaced-repetition/fsrs-rs/pull/251

FSRS is a time-series model.

The test files in `/tests/data`:

[collection.anki21.zip](https://github.com/tracel-ai/burn/files/15048830/collection.anki21.zip)

[revlog.csv](https://github.com/tracel-ai/burn/files/15048828/revlog.csv)

**Comment by antimora** [comment]
If you don't mind, can you also submit a community benchmark to compare your particular hardware?

https://burn.dev/benchmarks/community-benchmarks/

**Comment by L-M-Sherlock** [comment]
I have two devices: M1 with 16GB RAM and M2 Max with 96GB RAM. Could I run the benchmark in both devices?

**Comment by antimora** [comment]
> https://burn.dev/benchmarks/community-benchmarks/?user=InfiniteRemovability&os=Mac%20OS%2013%2E3%2E1%20%5B64%2Dbit%5D&version1=c0e975326c9bb861bc3179c10b9478f1f5021455&version2=c0e975326c9bb861bc3179c10b9478f1f5021455&search=true

Is this for the new version (0.15) or the previous? If you submitted for one version, do you mind running for the other?

**Comment by antimora** [comment]
The benchmarks can help baseline your hardware.

**Comment by L-M-Sherlock** [comment]
> Is this for the new version (0.15) or the previous? If you submitted for one version, do you mind running for the other?

I run it in the main branch c0e975326c9bb861bc3179c10b9478f1f5021455.

**Comment by L-M-Sherlock** [comment]
I run the benchmark on v0.13.2: https://burn.dev/benchmarks/community-benchmarks?user=InfiniteRemovability&os=Mac%20OS%2013%2E3%2E1%20%5B64%2Dbit%5D&version1=3bb0b8f473c7b98c95cf583b2b61cedb298ff306&version2=3bb0b8f473c7b98c95cf583b2b61cedb298ff306&search=true

The `from_data` of `ndarray` slows down ~7x:

<img width="604" alt="image" src="https://github.com/user-attachments/assets/63470277-c859-4baf-b9ba-5a03a2b59978">
