### ISSUE TITLE
shuffled dataset

### ISSUE THREAD

**Issue by wangjiawen2013** [tracel-ai/burn#2523]
Hi,
This is a chunk of code adopted from https://github.com/tracel-ai/burn/blob/main/examples/custom-image-dataset/src/training.rs
```rust
 let dataloader_train = DataLoaderBuilder::new(batcher_train)
     .batch_size(config.batch_size)
     .shuffle(config.seed)
     .num_workers(config.num_workers)
     .build(ImageFolderDataset::cifar10_train());
```
Does it shuffle the dataset only in current batch or the whole dataset in each epoch ?

**Comment by laggui** [comment]
When setting `.shuffle(seed)` with a dataloader, a [`ShuffledDataset`](https://burn.dev/burn-book/building-blocks/dataset.html) is used to shuffle the dataset item indices at each new epoch.
