### ISSUE TITLE
`ItemLazy` is a private trait and prevents custom output implementations

### ISSUE THREAD

**Issue by ImTheSquid** [tracel-ai/burn#2524]
**Describe the bug**
`ItemLazy` was introduced with #2521 but is crate-private, preventing outside output types from being used with the metrics system. This is a regression from previous behavior.

**To Reproduce**
Attempt to implement `ItemLazy` on a custom output type.

**Expected behavior**
I should be able to implement `ItemLazy` on my own custom output types.

**Comment by laggui** [comment]
Thanks for catching that! Fixed it :)
