### ISSUE TITLE
Broken tui rendering

### ISSUE THREAD

**Issue by SzczurekYT** [tracel-ai/burn#2580]
**Describe the bug**

It seems that the tui rendering is broken. (See the recording) 
I was able to reproduce it on two different machines with nobara linux (fedora fork), across 3 different terminal emulators - konsole, wezterm and the one builtin in vscode. The shell is zsh but iirc it is broken in bash too. I'm not sure what else can I add to help reproduce this. 

**To Reproduce**
 1. Run training with tui
 2. See artifacts

**Expected behavior**

Normal training tui

**Screenshots**

https://asciinema.org/a/5nQzV28pRJ1TD08Fd17TLIjq2

**Desktop (please complete the following information):**
 - OS: Fedora Linux

**Additional context**

**Comment by laggui** [comment]
Hmm that's weird. Looking at the recording it seems that there is a `"cl"` print statement messing up your TUI 😅 

Could that be in your code?

**Comment by SzczurekYT** [comment]
> Hmm that's weird. Looking at the recording it seems that there is a `"cl"` print statement messing up your TUI 😅 
> 
> Could that be in your code?

Yes, I'm fool 😅
I just noticed that.
I added it to model code to debug something, then got the code working, forgot completly about it and wondered why the tui is broken. Sorry

**Comment by laggui** [comment]
No worries! Happy to hear it was an easy fix 😄
