### ISSUE TITLE
#[derive(Module)] Module[Record|Item] types are public even when the module isn't

### ISSUE THREAD

**Issue by juntyr** [tracel-ai/burn#2608]
**Describe the bug**
I have a private struct that derives the `Module` trait. The generated `*Record` and `*Item` types are public (i.e. show up in documentation) even though the module itself isn't.

**To Reproduce**
1. Create a library crate
2. Create a private struct and derive the `Module` trait
3. Build the docs for the crate
4. The module struct isn't there (expected) but the generated `*Record` and `*Item` types are (unexpected)

**Expected behavior**
The generated structs should inherit the visibility of the module struct.

**Version**
burn 0.15.0

**Comment by laggui** [comment]
Makes sense, thanks for flagging that!

I just opened a quick PR that should resolve this issue. I validated by checking the macro expansion, but if you want to give it a shot you can check out the PR branch to try it with your stuff 🙂
