### ISSUE TITLE
Feature "audio" is not found

### ISSUE THREAD

**Issue by pmalex** [tracel-ai/burn#2631]
**Describe the bug**

A feature "audio" is presented in `burn-dataset` crate, but it is impossible to use it directly from `burn` crate.

**To Reproduce**

Make an empty binary rust project and add a line in Cargo.toml file:
```toml
[dependencies]
burn = { version = "~0.15", features = ["train", "audio"] }
```
You get error message:
```
error: failed to select a version for `burn`.
    ... required by package `burn_speech_commands_classifier v0.1.0 (/home/alex/Dev/burn_speech_commands_classifier)`
versions that meet the requirements `~0.15` are: 0.15.0

the package `burn_speech_commands_classifier` depends on `burn`, with features: `audio` but `burn` does not have these features.


failed to select a version for `burn` which could resolve this conflict
```

**Expected behavior**

Successfull compilation

**Desktop (please complete the following information):**
 - OS: [101-Ubuntu SMP]
 - Version [5.15.0-91-generic]

**Comment by laggui** [comment]
I just opened a PR to propagate the feature flag to the `burn` crate (similar to what is currently done for `vision`).

In the meantime, you can simply add `burn-dataset` to your Cargo.toml and enable the feature flag from there.

```toml
[dependencies]
burn = { version = "~0.15", features = ["train"] }
burn-dataset = { version = "0.15.0", features=["audio"] }
```

**Comment by pmalex** [comment]
@laggui, thank you for fix!

Speaking about workaround you've suggest: I've already tried this combination, but unfortunately, it leads to this error:
```sh
error[E0252]: the name `EnumCount` is defined multiple times
 --> C:\Users\alexg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\burn-dataset-0.15.0\src\audio\speech_commands.rs:9:29
  |
8 | use strum::EnumCount;
  |     ---------------- previous import of the macro `EnumCount` here
9 | use strum_macros::{Display, EnumCount, FromRepr};
  |                             ^^^^^^^^^--
  |                             |
  |                             `EnumCount` reimported here
  |                             help: remove unnecessary import
  |
  = note: `EnumCount` must be defined only once in the macro namespace of this module

For more information about this error, try `rustc --explain E0252`.
error: could not compile `burn-dataset` (lib) due to 1 previous error
```
It seems like we add the same code from two subcrates twice.
I also tried remove `burn` crate from dependency list and directly use `burn-core`, `burn-dataset`, `burn-train` etc. with various combination of features (including disable them), but it's not working.

Best decision that I came to is to use `HuggingfaceDatasetLoader` like in [this example](https://github.com/tracel-ai/burn/blob/a882843294ebbd725a634fef4e260c55856aef2b/crates/burn-dataset/examples/hf_dataset.rs).

If you know a better solution, I'll be glad to hear it.

**Comment by laggui** [comment]
Ahh that's weird, usually plays nice but didn't notice this issue with `EnumCount`. The proposed solution works on main thanks to some previous changes that alias the `strum::EnumCount`:

```rust
use strum::EnumCount as _;
use strum_macros::{Display, EnumCount, FromRepr};
```

If you want to use the last released version, looks like this works if you disable the dataset feature from burn (enabled by default)

```toml
[dependencies]
burn = { version = "0.15.0", default-features = false, features = ["train", "std"] }
burn-dataset = { version = "0.15.0", features=["audio"] }
```

**Comment by pmalex** [comment]
Yes, that's working, thanks!
