### ISSUE TITLE
ONNX:  Improve Error Reporting for Unsupported ONNX Operations

### ISSUE THREAD

**Issue by antimora** [Tracel-AI/burn#333]
### Description
Enhance the error reporting mechanism by providing a comprehensive list of unsupported ONNX operations encountered while loading a file, instead of stopping at the first error and displaying the error stack.

### Motivation
As `burn-import` currently supports a limited number of ONNX operations, users may experience frustration when encountering multiple errors one by one without clear guidance. By providing a complete list of unsupported operations, users can gain a better understanding of the issues at hand.

### Proposed Solution
When loading an ONNX file, identify all unsupported operations and display a helpful list to the user. This will improve user experience and provide clearer guidance on the limitations of the current implementation.

### Context

This is what the user sees:

```
error: failed to run custom build command for `onnx-inference v0.6.0 (/home/paul/projects/ai/burn/examples/onnx-inference)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/home/paul/projects/ai/burn/target/release/build/onnx-inference-e9fa340fe762a71e/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: VariantNotFound', burn-import/src/onnx/from_onnx.rs:375:63
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
     1: core::panicking::panic_fmt
               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
     2: core::result::unwrap_failed
               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1750:5
     3: core::result::Result<T,E>::unwrap
     4: burn_import::onnx::from_onnx::convert_node_proto
     5: burn_import::onnx::from_onnx::parse_onnx
     6: burn_import::onnx::to_burn::ModelSourceCode::new
     7: burn_import::onnx::to_burn::ModelGen::generate_model
     8: burn_import::onnx::to_burn::ModelGen::run
     9: burn_import::onnx::to_burn::ModelGen::run_from_script
    10: build_script_build::main
    11: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...

```

**Comment by antimora** [comment]
@nathanielsimard Do you think your PR has solved this issue https://github.com/burn-rs/burn/pull/363 or there is more to be done?

**Comment by nathanielsimard** [comment]
It could still be improved, I'll close it later after a few other refactoring from the ONNX parsing side.

**Comment by antimora** [comment]
I think we can close this ticket since we have made significant improvement to the error reporting.
