### ISSUE TITLE
Add other OSes/patforms for CI runs

### ISSUE THREAD

**Issue by antimora** [tracel-ai/burn#428]
Just like WONNX CI, we should add other targets and platforms for our CI actions. Here is the OS matrix for CI: https://github.com/webonnx/wonnx/blob/master/.github/workflows/rust.yml

**Comment by Luni-4** [comment]
Can we close this one @antimora?

**Comment by antimora** [comment]
Thank you, @Luni-4 and @syl20bnr, for your work with CI!
