### ISSUE TITLE
Implement interpolate function (inference only)

### ISSUE THREAD

**Issue by shanmo** [tracel-ai/burn#455]
### Feature description

Implement [interpolate](https://pytorch.org/docs/stable/generated/torch.nn.functional.interpolate.html?highlight=interpolate#torch.nn.functional.interpolate)

### Feature motivation

Interpolation is helpful for downsampling/upsampling the feature maps

**Comment by antimora** [comment]
Perfect. I think this could be also used by Resize operator filed here:  https://github.com/burn-rs/burn/issues/510

**Comment by antimora** [comment]
I'll implementing a first version with bicubic using convolution needed for resize onnx operator.

**Comment by Luni-4** [comment]
Is someone currently working on this function?

**Comment by nathanielsimard** [comment]
I don't think so, feel free to assign yourself if you want :)

**Comment by dcvz** [comment]
@Luni-4 did you build this in the end?

**Comment by Luni-4** [comment]
@dcvz 

Nope, I do not have much time in this period, if you want to implement that, no problem for me

**Comment by antimora** [comment]
Implementation using transpose Conv in pytorch: https://gist.github.com/mjstevens777/9d6771c45f444843f9e3dce6a401b183
