### ISSUE TITLE
 Refactor and Simplify Device Handling

### ISSUE THREAD

**Issue by antimora** [Tracel-AI/burn#461]
### Description
In the process of developing a Tensor module, it became clear that the current handling of device migration for modules can be improved and simplified. Specifically, the interaction between `to_device`, `map`, and `visit` methods is not intuitive and leads to confusion when trying to change the device of a module. 

Furthermore, we also found a problem with how the constant tensors are handled. It was observed that when the parent module is moved to a different device, the tensor field does not move to the new device. This needs to be addressed.

The code has evolved over time and seems to have been adapted to new requirements without a significant refactor. The team has recognized that there is a need for this code to be reviewed and restructured in order to simplify the mental model and minimize surprises for future developers.

### Steps

1. Refactor the device handling in the modules to improve and simplify the interaction between `to_device`, `map`, and `visit` methods.
2. Resolve the issue where the constant tensors do not move along with their parent module when changing devices.
3. Review and adjust the usage of the "B: Backend" reference in order to reduce confusion and align with the Rust standard lib behavior as closely as possible.
4. Perform an overall code review and refactor to simplify and clarify the codebase, keeping in mind the principle of adhering as closely as possible to the behaviors of "native" traits and derives in the Rust standard lib.

### Related Tickets

* https://github.com/burn-rs/burn/pull/459
* https://github.com/burn-rs/burn/issues/452

**Comment by louisfd** [comment]
@antimora Has this been addressed?

**Comment by antimora** [comment]
@louisfd i don't think it has been fixed. @nathanielsimard has done some refactoring in module that helped.
