### ISSUE TITLE
Addition of `abs` tensor opperator

### ISSUE THREAD

**Issue by antimora** [Tracel-AI/burn#506]
**Is your feature request related to a problem? Please describe.**

I'm frequently working with numerical computations involving tensors, where it often becomes necessary to compute the absolute values of all elements within a tensor. Currently, we do not have a straightforward method for this, leading to inconvenient workarounds.

**Describe the solution you'd like**

It would be beneficial to add a new `abs` operator in the tensor that works on tensor objects. This operator would compute and return a new tensor with the absolute values of each element from the original tensor.

**Describe alternatives you've considered**

```rust
let tensor = tensor.powf(2.0).sqrt();
```

**Additional context**

Many popular machine learning and numerical computation libraries (like TensorFlow, PyTorch, NumPy) support this operation out-of-the-box. Therefore, including this operator will bring our library more in line with established standards, improving the experience for users transitioning from other libraries.

**Comment by antimora** [comment]
> Can I work on this?

Go for it but be aware there is a serious learning curve mainly to understand the tensor and backend architecture. I am currently implementing `clamp` operator. I should be done by tomorrow and I'll have a PR that you can use as a guide. We do not have a documentation on this unfortunately. I might summed it up after I am done.

If you'd like to dive in and learn different parts of the system, it's a great way to do it.

**Comment by antimora** [comment]
@trfdeer, there is a simpler task for a start: https://github.com/burn-rs/burn/issues/487 if you want to give it a go.

**Comment by trfdeer** [comment]
Sure, I'll start with that

**Comment by mmalczak** [comment]
Hi
I have ready implementation, but still need a few checks. I will submit PR tomorrow probably.

**Comment by antimora** [comment]
@mmalczak , I have submitted PR for `clamp` operator if you need help/info: https://github.com/burn-rs/burn/pull/550 

I haven't written the details but I will.

**Comment by antimora** [comment]
@mmalczak assigned this ticket to you since you already have something written.

**Comment by antimora** [comment]
I believe this is done.
