### ISSUE TITLE
`meval` dependency requires `nom==1.2.4` which will be deprecated in the future. 

### ISSUE THREAD

**Issue by wdoppenberg** [Tracel-AI/burn#516]
**Describe the bug**
During compilation, the following warning is emitted:

```text
warning: the following packages contain code that will be rejected by a future version of Rust: nom v1.2.4
```

**To Reproduce**
Build the text-generation example.

**Expected behavior**
No warnings. 

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by wdoppenberg** [comment]
I just found your comment on the `meval` repository: https://github.com/rekka/meval-rs/issues/30 .

Feel free to remove this issue if you deem it redundant

**Comment by antimora** [comment]
Thanks for filing. Yes, we are aware of the warning but it's good to have an open issue ticket, so it's keep it open. 

This was brought it up in the existing issue to make the plot clear: https://github.com/burn-rs/burn/issues/211#issuecomment-1571206848 

We attempted (https://github.com/burn-rs/burn/pull/485) to replace it with `termplot` which solved the warning issue but still the plots were not clear. We were thinking to remove plots console altogether and replace with something like tensorboard or CometML (see https://github.com/burn-rs/burn/issues/382).

**Comment by antimora** [comment]
I believe this is fixed now since we moved to a new text based training.
