### ISSUE TITLE
`prod` and `prod_axis` tensor operators

### ISSUE THREAD

**Issue by wbrickner** [tracel-ai/burn#526]
### Feature description

Product of all elements in a tensor, and those along a given axis, just like we have `sum` and `sum_axis`.

### Feature motivation

Basic tensor operation missing. I personally need it for some ML research.

### (Optional) Suggest a Solution

Current workaround is `tensor.log().sum().exp()`, but this is slower and should not be required of the end user.

---

It would also be nice, although it is a separate matter, to have function to sum/prod along multiple axes at once in parallel. Otherwise you need to do two sequential tensor operations which reduces parallelism utilization.

For instance, a 3D tensor could be summed along its first two axes, perhaps like `tensor.sum_axes([0, 1]);`, or `tensor.prod_axes([1, 3])`.

**Comment by antimora** [comment]
Linking someone's attempt to implement this: https://github.com/tracel-ai/burn/pull/1173
