### ISSUE TITLE
[RFC]: Continuous Integration Design 

### ISSUE THREAD

**Issue by Luni-4** [tracel-ai/burn#552]
This issue is an extension of #428 and it is an RFC to verify if there is a consensus with this new design

### Feature description

A new design for continuous integration might be the following one:
- [x] One job for code formatting and linting issues
- [x]  One job that runs all `std` tests on `Linux`
- [x] One job that runs all `std` tests on `MacOs` (@dcvz)
- [x] One job that runs all `std` tests on `Windows` (@syl20bnr)
- [x] One job that runs all `no-std` tests

Let's try to tackle each point one-by-one

- (1) Some `GitHub` actions allow to visualize `clippy` lints and bad formatting as messages in a PR or in a report. This approach reduces the time spent in detecting these problems because they are immediately viewable. A contributor, especially a new one, does not have to scrape through CI logs in order to find them. This job could run **only** on a Linux operating system. Running this job on more operating system could be a waste of resources.

- (2, 3, 4) Run all current checks and tests on the specific operating system using a script. The `run-checks.sh` script could be rewritten in `Rust` language in order to be cross-platform and less error-prone. Collect code coverage data through Rust source code coverage and then aggregate the results using [grcov](https://github.com/mozilla/grcov), finally publish this data on [codecov](https://about.codecov.io/) in order to immediately visualize which lines of code are **not** covered by tests. (thanks to @gonzalesMK for the help)

- (5) Maintain the same checks which are already performed. Even this job will benefit from `run-checks.sh` rewriting in `Rust`.

### Feature motivation

Having a Continuous Integration that implements the points described above, in my opinion, reduces the effort in code maintainability, making the development more interesting, also decreases the possibility to have problems in the future.

**Comment by Luni-4** [comment]
What we still have to implement :

- [ ] Use GitHub Actions [filters](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#using-filters) to avoid running CI for nothing
- [ ] Implement `Grcov` checks **ONLY** on CI
- [ ] Try another strategy to run `clippy` on CI
- [ ] Add MacOS and Windows configurations through matrix

**Comment by gonzalesMK** [comment]
@Luni-4  I have 2 points to consider:

1. Should we run Rust Doc just once on the same job as Rust Clippy? 
2. Can we minimize running coverage? Maybe run coverage in Linux jobs and then run coverage for specific packages on other OS?

**Comment by gonzalesMK** [comment]
1. Yeah, I just meant to keep like that. I think I misread the first post because I thought the doc was going to run for windows/mac/linux. :+1: 

Besides, should I close this PR https://github.com/burn-rs/burn/pull/797 , so to implement this RFC in a new PR ?

**Comment by Luni-4** [comment]
@gonzalesMK 

Perhaps we can transform each bullet point into a PR, in this way it would be simpler to review. What do you think?

**Comment by Luni-4** [comment]
@nathanielsimard

Yep, the `mold` idea is contained in the link provided by @gonzalesMK

**Comment by gonzalesMK** [comment]
> Perhaps we can transform each bullet point into a PR, in this way it would be simpler to review. What do you think?

Sounds good to me.

**Comment by Luni-4** [comment]
Thanks to @gonzalesMK, @dcvz, and @syl20bnr this issue can be closed! Congrats to everyone for your work and help!
