### ISSUE TITLE
if you want use Sequential，you can look here

### ISSUE THREAD

**Issue by Zheby** [tracel-ai/burn#583]
if i have "Conv","C2f","SPPF","Bottleneck".net
you can look it:
```
enum SequentialType<B:Backend>{
    Conv(Conv<B>),
    C2f(C2f<B>),
    SPPF(SPPF<B>),
    Bottleneck(Bottleneck<B>)
}
struct Sequential<B:Backend>{
    layers:Vec<SequentialType<B>>
}

impl <B:Backend>Sequential<B> {
    fn new() -> Sequential<B> {
        Self{
            layers: vec![],
        }
    }
    fn add(mut self,layer:SequentialType<B>){
        self.layers.push(layer)
    }
    fn forward(&self, input:Tensor<B,4>) -> Tensor<B, 4> {
        let mut x = input.clone();
        for i in self.layers{
            match i{
                SequentialType::Conv(k) => {
                    x = k.forward(x)
                }
                SequentialType::C2f(k) => {
                    x = k.forward(x)
                }
                SequentialType::SPPF(k) => {
                    x = k.forward(x)
                }
                SequentialType::Bottleneck(k) => {
                    x = k.forward(x)
                }
            }
        }
        return x;
    }
}
```

**Comment by antimora** [comment]
Thank you for sharing this how-to. We should add a section in the book on how to have a sequential forwards. @nathanielsimard , @louisfd, would you agree? 

Also related, we have an enhancement ticket for allowing enum modules, please see: https://github.com/burn-rs/burn/issues/726

**Comment by nathanielsimard** [comment]
@antimora I'm not sure this is ready to go on the book. We may find better options with proper support beforehand.

**Comment by finnkauski** [comment]
Does this deserialise well from pytorch Sequential?

**Comment by antimora** [comment]
> Does this deserialise well from pytorch Sequential?
> 
> Edit: `SequentialType` needs to implement Module.

Please give a try. Probably we need to update our PyTorchRecorder. I haven't tested this particular use case. If you can provide me with a minimal example, I can fix it.

**Comment by antimora** [comment]
@finnkauski , here is an open issue ticket for Enum modules: https://github.com/tracel-ai/burn/issues/726

**Comment by zemelLeong** [comment]
How to embed `sequential` into `module`. 
```rust {.line-numbers}
enum SequentialType<B: Backend> {
    Conv2d(Conv2d<B>),
    BatchNorm2d(BatchNorm<B, 2>),
    BasicBlock(BasicBlock<B>),
    Sequential(Sequential<B>),
}

struct Sequential<B: Backend> {
    layers: Vec<SequentialType<B>>,
}

impl<B: Backend> Sequential<B> {
    fn new() -> Self {
        Self { layers: Vec::new() }
    }

    fn add(&mut self, layer: SequentialType<B>) {
        self.layers.push(layer);
    }

    fn forward(&self, x: Tensor<B, 4>) -> Tensor<B, 4> {
        let mut x = x;
        for layer in &self.layers {
            match layer {
                SequentialType::Conv2d(conv) => x = conv.forward(x),
                SequentialType::BatchNorm2d(bn) => x = bn.forward(x),
                SequentialType::BasicBlock(block) => x = block.forward(x),
                SequentialType::Sequential(sequential) => x = sequential.forward(x),
            }
        }
        x
    }
}

#[derive(Module, Debug)]
pub struct BasicBlock<B: Backend> {
    expansion: usize,
    bn_momentum: f64,
    conv1: Conv2d<B>,
    bn1: BatchNorm<B, 2>,
    relu: ReLU,
    conv2: Conv2d<B>,
    bn2: BatchNorm<B, 2>,
    downsample: Sequential<B>,
    stride: usize,
    planes: usize,
}
```
```
error[E0277]: the trait bound `Sequential<B>: Module<B>` is not satisfied
  --> src\lore_dector.rs:43:10
   |
43 | #[derive(Module, Debug)]
   |          ^^^^^^ the trait `Module<B>` is not implemented for `Sequential<B>`
   |
   = help: the following other types implement trait `Module<B>`:
             bool
             i8
             i16
             i32
             i64
             usize
             u8
             u16
           and 60 others
   = note: required for `std::option::Option<Sequential<B>>` to implement `Module<B>`
   = note: this error originates in the derive macro `burn::serde::Deserialize` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `Sequential<B>: Module<B>` is not satisfied
  --> src\lore_dector.rs:44:12
   |
44 | pub struct BasicBlock<B: Backend> {
   |            ^^^^^^^^^^^^^^^^^^^^^^ the trait `Module<B>` is not implemented for `Sequential<B>`
   |
   = help: the following other types implement trait `Module<B>`:
             bool
             i8
             i16
             i32
             i64
             usize
             u8
             u16
           and 60 others
   = note: required for `std::option::Option<Sequential<B>>` to implement `Module<B>`
note: required because it appears within the type `BasicBlockRecord<B>`
```

**Comment by laggui** [comment]
> How to embed `sequential` into `module`.
> 
> ```rust
> enum SequentialType<B: Backend> {
>     Conv2d(Conv2d<B>),
>     BatchNorm2d(BatchNorm<B, 2>),
>     BasicBlock(BasicBlock<B>),
>     Sequential(Sequential<B>),
> }
> 
> struct Sequential<B: Backend> {
>     layers: Vec<SequentialType<B>>,
> }
> 
> impl<B: Backend> Sequential<B> {
>     fn new() -> Self {
>         Self { layers: Vec::new() }
>     }
> 
>     fn add(&mut self, layer: SequentialType<B>) {
>         self.layers.push(layer);
>     }
> 
>     fn forward(&self, x: Tensor<B, 4>) -> Tensor<B, 4> {
>         let mut x = x;
>         for layer in &self.layers {
>             match layer {
>                 SequentialType::Conv2d(conv) => x = conv.forward(x),
>                 SequentialType::BatchNorm2d(bn) => x = bn.forward(x),
>                 SequentialType::BasicBlock(block) => x = block.forward(x),
>                 SequentialType::Sequential(sequential) => x = sequential.forward(x),
>             }
>         }
>         x
>     }
> }
> 
> #[derive(Module, Debug)]
> pub struct BasicBlock<B: Backend> {
>     expansion: usize,
>     bn_momentum: f64,
>     conv1: Conv2d<B>,
>     bn1: BatchNorm<B, 2>,
>     relu: ReLU,
>     conv2: Conv2d<B>,
>     bn2: BatchNorm<B, 2>,
>     downsample: Sequential<B>,
>     stride: usize,
>     planes: usize,
> }
> ```
> 
> ```
> error[E0277]: the trait bound `Sequential<B>: Module<B>` is not satisfied
>   --> src\lore_dector.rs:43:10
>    |
> 43 | #[derive(Module, Debug)]
>    |          ^^^^^^ the trait `Module<B>` is not implemented for `Sequential<B>`
>    |
>    = help: the following other types implement trait `Module<B>`:
>              bool
>              i8
>              i16
>              i32
>              i64
>              usize
>              u8
>              u16
>            and 60 others
>    = note: required for `std::option::Option<Sequential<B>>` to implement `Module<B>`
>    = note: this error originates in the derive macro `burn::serde::Deserialize` (in Nightly builds, run with -Z macro-backtrace for more info)
> 
> error[E0277]: the trait bound `Sequential<B>: Module<B>` is not satisfied
>   --> src\lore_dector.rs:44:12
>    |
> 44 | pub struct BasicBlock<B: Backend> {
>    |            ^^^^^^^^^^^^^^^^^^^^^^ the trait `Module<B>` is not implemented for `Sequential<B>`
>    |
>    = help: the following other types implement trait `Module<B>`:
>              bool
>              i8
>              i16
>              i32
>              i64
>              usize
>              u8
>              u16
>            and 60 others
>    = note: required for `std::option::Option<Sequential<B>>` to implement `Module<B>`
> note: required because it appears within the type `BasicBlockRecord<B>`
> ```

You need to `#[derive(Module)]`.

We just added support for enum modules in #1337. You can use the latest version on main to do something like [this](https://github.com/tracel-ai/burn/blob/main/crates/burn-core/tests/derive_module.rs#L37-L41):

```rust
#[derive(Module, Debug)]
enum SequentialType<B: Backend> {
...
}

#[derive(Module, Debug)]
struct Sequential<B: Backend> {
    layers: Vec<SequentialType<B>>,
}
```
