### ISSUE TITLE
Make burn-wgpu no_std compatible

### ISSUE THREAD

**Issue by antimora** [Tracel-AI/burn#595]
### Feature Description

Enable `burn-wgpu` to be `no_std` compatible, allowing for compilation to the `wasm32` target.

### Motivation for the Feature

For the `burn-wgpu` backend to be utilized in browsers, it needs to be compiled for the `wasm32` target, which doesn't employ the `std` module.

### Proposed Solution

Eliminate all references to `std` and replace them with `core`, mirroring the approach taken for `burn-ndarray`.

**Comment by antimora** [comment]
(tagging @Gadersd)

**Comment by nathanielsimard** [comment]
I don't think [wgpu](https://github.com/gfx-rs/wgpu) supports `no-std`, but I don't think it's necessary to compile to `wasm32`. Some `std` modules don't compile to `wasm` (net and fs), but a lot do compile:

https://github.com/rustwasm/wasm-bindgen/blob/a210654ac3f89b9ef11f1d3eb0ee2c9eaa814021/guide/src/reference/rust-targets.md?plain=1#L9

**Comment by antimora** [comment]
@nathanielsimard, true but we have to make sure burn-wgpu itself can be compiled with no_std. There might be some math operation that we missed or other small things that is hard to get around. We will just make sure it is compatible and remains compatible. 

So the scope of the work is to make sure burn-wgpu is no_std compatible with possibly with all libs used (if wgpu is not, then it's on them and we will provide documentation how to add stubs like with wasm-bindgen).

**Comment by antimora** [comment]
I believe this is already done.
