### ISSUE TITLE
 Enhance `ModelGen` in `burn-import` to Support Various Record Files and Precision Formats

### ISSUE THREAD

**Issue by antimora** [Tracel-AI/burn#657]
#### Issue:

The current implementation of `ModelGen` in `burn-import` supports saving files with an absolute path, pointing to the target output. This has some limitations, and we need to extend this functionality to support different record files and precision to enhance the usability and flexibility of the module. The proposed enhancements are:

#### Requirements:

1. **Support for Bincode File Format**: The user should be able to save the record file in Bincode format. This will allow the file to be included in the binary executable using the `include_bytes!` macro, making the handling of binary data more convenient.

2. **Precision Specification**: Users must be able to specify the precision of the record file. Both half precision and full precision should be supported, allowing for optimization in terms of storage and computational resources.

3. **Include File with Binary Executable**: The record file should be included along with the binary executable, ensuring that all necessary files are bundled together.

#### Impact:

These enhancements will improve the efficiency and flexibility of `ModelGen`, allowing users to handle various file formats and precision types. This would align `burn-import` with modern standards and best practices, making it more versatile for different use cases.

#### Proposed Solution:

- Modify the `ModelGen` class to accept file format and precision as parameters.
- Implement the necessary logic to handle Bincode file saving and precision specification.
- Update the documentation and examples to reflect these changes.

#### Acceptance Criteria:

- The user can save the record file in Bincode using the `include_bytes!` macro.
- The user can specify the precision (half/full) for the record file.
- The record file is included along with the binary executable.

**Comment by antimora** [comment]
@mrvollger, @Luni-4, please be aware of the current limitation of burn-import. I'll be working on this next to enhance the format. I'll be needing this feature for my Web demo.

**Comment by nathanielsimard** [comment]
I believe we should enhance the names of functions used for instantiating a model. In my view, it's not apparent that using `new` initializes the model without pre-trained weights, whereas `default` initializes the model with pre-trained weights.

As we work on refining the names, it would also be valuable to generate detailed documentation that clarifies these aspects.

**Comment by antimora** [comment]
This is done.
