### ISSUE TITLE
Use `AsRef<Path>` instead of `&str` for file operations

### ISSUE THREAD

**Issue by Colerar** [tracel-ai/burn#698]
e.g.

https://github.com/burn-rs/burn/blob/fb2a71bb81e1a688b4cdae38729b24dd9361283f/burn-core/src/config.rs#L47

This allow caller pass `PathBuf`, `String`, `&str` and [all types implemented `AsRef<Path>`](https://doc.rust-lang.org/stable/std/convert/trait.AsRef.html#implementors), and it's API-compatible, it won't break any existing code.

**Comment by antimora** [comment]
I agree.

Should we search all places where it's used, or do we know where it is used already?

**Comment by nathanielsimard** [comment]
I think we should search for more usage, especially regarding saving configuration in JSON.

**Comment by ivnsch** [comment]
I'll give this a go.

**Comment by laggui** [comment]
Seems like this was completed in #699 and #1919
