### ISSUE TITLE
Runtime backend selection

### ISSUE THREAD

**Issue by MOZGIII** [tracel-ai/burn#705]
### Feature description

The ability to select the backend at runtime, and ergonomically switch between the backends in the code using dynamic dispatch.

### Feature motivation

Because when I use burn I want to build portable applications, not something that is tied to just one platform. Also, to be able to execute the same model under different runtimes.

### Suggest a Solution

Here is what my experiments (https://github.com/MOZGIII/burn-select) have shown so far:
- Backend-specific element traits must be exposed (addressed by https://github.com/burn-rs/burn/pull/700)
- `burn_tensor::backend::Backend` is not object-safe, meaning you can't turn it into the `dyn Backend`; a more in-depth look shows that to achieve this we'd need to restructure the traits, in particular, to avoid depending on the `OtherTrait<Self>` where `OtherTrait<T: Backend>`.

There might be more work required, and in that case, I'll be adding more items to the Progress tracking section (see below).

## Progress tracking

- [x] #700
- [ ] Refactor the `Backend` and surrounding core traits to enable object-safety

**Comment by antimora** [comment]
This might be difficult to achieve because the model is tied to a backend statically. Wouldn't it be easier to have separate instances of a model with different backend?

**Comment by MOZGIII** [comment]
Well, this is exactly my point - the current state of things is not great, and we can do much better.

---

> Wouldn't it be easier to have separate instances of a model with different backend?

Well, it would not be easier, but it is the only way. So, that would be using a generic fn for the main application code, and monomorphising all the possible generic variants.

This is actually a nightmare to support and requires a suite of macros to avoid writing the same code twice. The issue though is, effectively, instead of relying on strictly traits, the monomorphic evaluation of all branches is concrete - i.e. you effectively have to have all those branches implemented somehow. If done by hand instead of via a macro - this would allow the use of custom code per backend in the respective backend branch. This is not a problem on its own, but this can lead to a further decrease of the quality of the interfaces if relied on by the trait designers.

Ultimately, the longer the traits are not asserted for the composability - the worse the situation will become throughout the maintenance. It is already in a stage where quite a lot of API changes would be required to fix it. The good thing though is the current API has very few ways to sanely use the traits for some non-trivial composition, so no real users will likely be harmed.

---

If you'd like to see how the separate instances design works, take a look at my code here: https://github.com/MOZGIII/netsound/blob/master/netsound/src/audio_backend_config.rs
I am talking from experience here, that is a similar design, and it's not pretty. The difference is there I am writing an app, not a lib, so I am not forcing the users to opt-in for all that complexity, but rather choosing that for just myself.

---

The reason why I am doing it there is because it is audio software, and the code can't just run all behind the dyn trait call due to how system APIs are laid out - the callbacks for handing audio buffers have to operate in real-time in the context switches, and an extra longjump caused by dyn trait can hurt. But burn is different, and doesn't really have this concern, given how it operates with the backends it should have much tighter and hotter loops that the CPU can cache where it matters.
Well, at least that's what my understanding of the matter is, and that's how I would rationalize using a dyn trait backend in my app.

**Comment by nathanielsimard** [comment]
Making the backend trait `dyn` is a no-go. A lot of the benefits of the backend trait come from the fact that it uses static dispatch, and you **can't** call operations with two tensors on different backends. Each backend exposes **its** set of precision that it can use, so there are no errors of the kind: _half precision isn't supported on the CPU device_ or _Tensor one is on backend Tch, but the other is on backend NdArray_.

Your use case is valid though, but it's more **linked** to changing the backend of a model **efficiently**.

```rust
let model1 = // on backend 1;
let device = // backend 2 device;
let model2 = model1.to_backend::<Backend2>(device);
```

This should be **feasible**, but each backend can specialize the conversion implementation for each possible backend. With that conversion implemented, you could easily implement switching the backend during runtime. However, even today, you can create an enum of models with different backends:

```rust
enum MyModel {
   NdArray(Model<NdArrayBackend<f32>>),
   Tch(Model<TchBackend<f32>>),
   Wgpu(Model<WgpuBackend<Vulkan, f32, i32>>),
}
```

You could also implement a backend conversion today using the bytes recorder (`BytesRecorder`) to convert the weights into bytes, then reload them into another backend—no precision error possible :).

```rust
impl MyModel {
   fn convert_ndarray(self) -> Self {
       match self {
           NdArray(model) =>  model,
           Tch(model) => {
               let bytes = BinBytesRecorder<FullPrecisionSettings>::record(model.into_record());
               let record = BinBytesRecorder<FullPrecisionSettings>::load(bytes); // Type inference should do its job.
               Self::NdArray(Model::init_with(config, record))
            },
            ...
       }
   }
}
```

The goal with the backend conversion issue should be to implement a more efficient way of changing the backend than to serialize and deserialize weights into bytes. But it's a start.

Regarding compositionality and maintainability, I would argue that not using `dyn` is a big plus. Erasing types can lead to a lot of problems and limit the abstraction features you can use – a lot of extremely good features. For example, while using traits that can be turned into objects, you can't abstract types with associated types, which is extremely constraining, as abstracting type and how memory works is one of the best features of Rust.

In all cases, the use case of changing the backend of a model dynamically is important! We should implement an easy-to-use API and document it. No macros or weird techniques should be used to achieve that; it should just work!

**Comment by MOZGIII** [comment]
> Making the backend trait `dyn` is a no-go. A lot of the benefits of the backend trait come from the fact that it uses static dispatch, and you **can't** call operations with two tensors on different backends. Each backend exposes **its** set of precision that it can use, so there are no errors of the kind: _half precision isn't supported on the CPU device_ or _Tensor one is on backend Tch, but the other is on backend NdArray_.

This is not a limitation for having a dyn trait. On the contrary - it is super elegant, you'd just restrict the code to the exact type you need: `dyn Backend<Element = f32>`.

The way users would use it is they would request any backend with the given required shape of the element. This is obviously not something that can be chosen at runtime.

> Regarding compositionality and maintainability, I would argue that not using `dyn` is a big plus. Erasing types can lead to a lot of problems and limit the abstraction features you can use – a lot of extremely good features. For example, while using traits that can be turned into objects, you can't abstract types with associated types, which is extremely constraining, as abstracting type and how memory works is one of the best features of Rust.

`dyn Trait` does not mean erasing the types. Also, yes, the associated types would have to also be dyn traits - but I don't see how it would create issues with how the memory works. You don't have to do anything that you wouldn't been able to do without dyn traits. I already explained the possible concerns that I see, and in essence, there should be no issues. You don't have to use `Box` everywhere if that's what you're worried about - placing dyn objects on a stack is an option too.

---

### The essence of the issue

My issues in not with making the model instances - it is with making a backend itself.

What I want is to implement the following:

```
type BoxedBackend<T> = Box<dyn Backend, Element = T>;

backend_select::from_env<T>() -> Result<BoxedBackend<T>, ...>;
backend_select::from_clap<T>(clap_args: clap::Args) -> Result<BoxedBackend<T>, ...>;
backend_select::from_config<T>(cfg: ...) -> BoxedBackend<T>;
```

just, essentially, abstracting the backend creation.

Without the dyn traits, this could work too:

```
// Magic can be kept out of scope here, see my repo for more info.
enum SelectBackend<Element, Magic> {
  NdArray(NdArrayBackend<Element>),
   Tch(TchBackend<Element>>),
   Wgpu(WgpuBackend<Magic, Element, Magic>),
}

// no just `Backend`, but all of the dependent traits too
impl Backend for SelectBackend {
  // here all the calls are implemented via `match` branching - and
  // this is where the insanity comes in, and macros are required
  
  // or you could just do it manually - which would be an insane amount of relatively repetitive code
}

backend_select::from_env<T>() -> Result<SelectBackend<T>, ...>;
backend_select::from_clap<T>(clap_args: clap::Args) -> Result<SelectBackend<T>, ...>;
backend_select::from_config<T>(cfg: ...) -> SelectBackend<T>;
```

So, this. This is where the problem is.

- `dyn Backend` doesn't work
- `enum`-based `Backend` is super annoying to implement; also, if you dig deeper than I did, it might even be impossible to do.

---

### On the order of importance of this

As with anything else, you either provide something out of the box if it can be generalized enough, or you essentially make everyone who needs it to have one write their own specialized version. In this case, the backend construction *can* actually be generalized. It does not have to be trait-driven (i.e. no need to add a `FromConfig` trait) - or it could be! That's beside the point here - as while there is no way to represent multiple backends as a single object (dyn trait or enum) this whole thing won't work.

Doing the `Model { Backend1: Model<Backend1>, Backend2: Model<Backend2>, }` is making users implement this. They still won't be able to abstract around any backend, they'll just write a specialized variant they need. It will likely be a huge code duplication.

---

### On the `enum`-based backend maintenance

The annoyance of the `enum`-based `Backend` backend means that maintaining it outside of the `burn` repo (i.e. in a separate repo as I tried) would be a maintenance hell, as for any API change multiplied by a backend addition there would be a change required to that external crate. It would be much easier to pack those changes together in a monorepo-style atomic changes. So, the best way would be to contribute the backend abstraction to the core. That way every change can be done with whatever the implementation for dynamic backend selection is.

---

### On the `Element` shapes

Again, to emphasize: I am *not* talking about having the backend be abstracted around the shape of the data, i.e. no `dyn Element`. The element would still be a concrete, explicit requirement for the `Backend` (where needed of course).

`dyn Element` is a whole different topic, and I don't have a particular interest in it cause I have no need for that. In reference to my previous comments, I am more interested in comparing how backends compare (i.e. f32 wgpu vs f32 tch) cause there might be bugs in the backends. Actually, this is what I am experiencing locally, and to debug this I needed a neat way to switch backends - but I'll start another issue on this later on.

---

Please consider this with an open mind, as I don't mean any harm, and merely just trying to provide some improvements I see fit. In my mind, the added elegance we could achieve with proper API refactoring optimizing for composability will be immense. But before doing this work, I know I need to justify it and get people on board. I don't like working on the code just to throw it away, you know :D

**Comment by nathanielsimard** [comment]
> This is not a limitation for having a dyn trait. On the contrary - it is super elegant, you'd just restrict the code to the exact type you need: dyn Backend<Element = f32>.

This would not work. All associative types must be known to be static; thus, it would be `dyn Backend<IntElem = i32, FloatElem = f32, TensorPrimitive<const D: usize> = TchTensor<D, f32>, IntTensorPrimitive<const D: usize> = TchTensor<D, i32>, BoolTensorPrimitive<const D: usize> = TchTensor<D, bool>, Device = TchDevice>`. This isn't user-friendly or even possible due to const generics. You can add a constraint to the backend trait if you want:

```rust
fn function<B: Backend<FloatElem = f32>>(tensor: Tensor<B, 2>);
```

What I'm trying to communicate is that the Backend trait can't be created as an object; it is designed not to be. It is designed to easily create backend implementations without any forced pattern. It's a collection of types and functions where backend implementations have complete control.

> dyn Trait does not mean erasing the types. Also, yes, the associated types would have to also be dyn traits - but I don't see how it would create issues with how the memory works. You don't have to do anything that you wouldn't been able to do without dyn traits. I already explained the possible concerns that I see, and in essence, there should be no issues. You don't have to use Box everywhere if that's what you're worried about - placing dyn objects on a stack is an option too.

The associated types have no constraints except for being `Send + Sync + Clone` and similar traits. These aren't objects either; they represent how a backend stores buffers and handles Tensor memory. It can be seen as a tensor handle. The backend implementation decides this.

> My issues in not with making the model instances - it is with making a backend itself.

Perhaps we need better documentation, but backends shouldn't be created; they should be injected as types, not instances.

> Doing the Model { Backend1: Model<Backend1>, Backend2: Model<Backend2>, } is making users implement this. They still won't be able to abstract around any backend, they'll just write a specialized variant they need. It will likely be a huge code duplication.

I'm not sure I understand. You implement a model once with a generic backend, and you can instantiate it on any backend. There is no code duplication in that scenario. We might need to provide a way to change the model's backend during runtime, but it doesn't require changes to the Backend trait.

> On the enum-based backend maintenance The annoyance of the enum-based Backend backend means that maintaining it outside of the burn repo (i.e. in a separate repo as I tried) would be a maintenance hell, as for any API change multiplied by a backend addition there would be a change required to that external crate. It would be much easier to pack those changes together in a monorepo-style atomic changes. So, the best way would be to contribute the backend abstraction to the core. That way every change can be done with whatever the implementation for dynamic backend selection is.

I don't think an enum-based backend is a good idea. We want the following to never compile:

```rust
let tensor_backend1 = ...;
let tensor_backend2 = ...;
let output = tensor_backend1.matmul(tensor_backend2); // Should never compile
let output = tensor_backend1.to_backend::<Backend2>().matmul(tensor_backend2); // Explicit conversion needed to compile.
```

This means that in your application logic, you need to determine which part is responsible for changing the backend. This type will probably need to be generic over two backend types for the transformation, similar to to_device, but statically checked. We already have type checks for autodiff backend using a similar approach.

> Please consider this with an open mind, as I don't mean any harm, and merely just trying to provide some improvements I see fit. In my mind, the added elegance we could achieve with proper API refactoring optimizing for composability will be immense. But before doing this work, I know I need to justify it and get people on board. I don't like working on the code just to throw it away, you know :D

Of course, written arguments might seem defensive or even critical, but I appreciate that people use burn and share their use cases. This helps the framework improve over time :). It's also a great idea to communicate your intentions and use cases before implementing them!

I also want to emphasize that I still think runtime backend selection should be possible and user-friendly. It's something I was already considering, but without changing the fundamental philosophy of the backend trait as a collection of types and functions. In Rust, coming from object-oriented languages, dynamic dispatch is good for abstracting behavior but not well-suited for abstracting data (types). Dependency injection in Rust often involves using generic arguments rather than passing objects as parameters.

**Comment by MOZGIII** [comment]
> What I'm trying to communicate is that the Backend trait can't be created as an object; it is designed not to be. It is designed to easily create backend implementations without any forced pattern. It's a collection of types and functions where backend implementations have complete control.

I understand you.

All I am saying is that we currently have a bad design that can be improved. Not that your goals are bad design, but the current implementation is. I am completely on board with having to restrictions on backend implementations - that would not be necessary. It is just the structure of the core traits that we'll have to alter - it would hardly limit the flexibility of the said traits or backends down the line. I really don't think it would have any downsides except a bit more decoupled traits - i.e. we might have to further split the `Backend` trait, and get rid of the oddities of `: OtherTrait<Self>` deps.
Also, don't forget we can do `impl X for dyn Trait` - this is the key to supporting the dyn traits the way I see it.

This is a practical discussion though, and I'd be happy to focus on it if the more general concerns (justification) are covered.

> I don't think an enum-based backend is a good idea. We want the following to never compile:

That still wouldn't compile though, right? `dyn Trait` != `T: Trait` for this purpose. With enum-based backend, it won't be an issue either, because the 

> Of course, written arguments might seem defensive or even critical, but I appreciate that people use burn and share their use cases. This helps the framework improve over time :). It's also a great idea to communicate your intentions and use cases before implementing them!

🔥 👍 

> I also want to emphasize that I still think runtime backend selection should be possible and user-friendly. It's something I was already considering, but without changing the fundamental philosophy of the backend trait as a collection of types and functions. In Rust, coming from object-oriented languages, dynamic dispatch is good for abstracting behavior but not well-suited for abstracting data (types). Dependency injection in Rust often involves using generic arguments rather than passing objects as parameters.

Well, the collection of traits is the way to roll as far as I'm concerned. There is no need to get rid of that part.

Is there a particular difficulty you have in mind that I'm not seeing? It doesn't look like it would be a problem at all... It might even be an improvement to a degree, as we have the potential to make the relationship between the traits more explicit and the traits themselves loosely coupled at the same time.

The only serious issue with this project that I see is it will be a breaking change for external backend implementations, but it might actually be fine this early in the project (i.e. pre 1.0.0).

**Comment by nathanielsimard** [comment]
> All I am saying is that we currently have a bad design that can be improved. Not that your goals are bad design, but the current implementation is. I am completely on board with having no restrictions on backend implementations - that would not be necessary. It is just the structure of the core traits that we'll have to alter - it would hardly limit the flexibility of the said traits or backends down the line. I really don't think it would have any downsides except a bit more decoupled traits - i.e. we might have to further split the Backend trait, and get rid of the oddities of : OtherTrait<Self> deps.

I don't believe the current design is bad. In fact, quite the opposite! For an overview of Burn's philosophy, please take a look at the [motivation](https://github.com/burn-rs/burn/blob/main/burn-book/src/motivation.md) section. While I wouldn't claim it's flawless, I don't find it to be fundamentally wrong. Additionally, it's important to recognize that different people may have preferences for varying designs with different trade-offs. Functional enthusiasts tend to minimize their use of state and dynamic traits, opting for mappers over mutable data structures. Burn falls somewhere between these two approaches, leaning a bit more towards the functional side with greater emphasis on static dispatch over dynamic dispatch. This isn't indicative of poor design; rather, it brings forth numerous benefits.

> That still wouldn't compile though, right? dyn Trait != T: Trait for this purpose. With enum-based backend, it won't be an issue either, because there is a single and distinct type.

Using an enum for the backend merely hide the issue. Consider a scenario where the left-hand side tensor resides in backend 1 (enum variant), while the right-hand side is in backend 2 (another enum variant). In such a situation, the program will compile, but it will lead to a panic! being required, or potentially worse, an implicit backend conversion. This conversion could potentially mask code problems and result in significant performance bottlenecks.

> The only serious issue with this project that I see is it will be a breaking change for external backend implementations, but it might actually be fine this early in the project (i.e. pre 1.0.0).

Yes, it doesn't matter that much in the current state. If there are changes to be made, it's better to make them now rather than waiting for a year.

Before attempting any implementation, ensure you share your new API for the intended use case. Based on the links you provided, it seems like you're trying to use configurations (perhaps provided through environment variables or files) to choose the backend. However, it's important to understand that selecting a backend isn't an executable task; instead, the configuration should revolve around configuring the instantiation of a module on __a backend__. A common and even recommended approach is to abstract the prediction tool you are actually using:

```rust
/// This trait can be dynamic.
trait MyTask { 
    fn predict(&self, features: FeatureType) -> PredictionType;
}

impl<B: Backend> MyTask for Model<B> {
   fn predict(&self, features: FeatureType) -> PredictionType {
       let tensor = features.into_tensor();
       let output = self.forward(tensor);
       
       PredictionType::from_tensor(output)
   }
}

fn create_model(config: Config) -> Box<dyn MyTask> { // Can also use Arc; Burn modules are thread-safe :)
    match config.backend {
        "tch" => Box::new(Model::<TchBackend<f32>>::init_with(..)),
         "ndarray" => Box::new(Model::<NdArrayBackend<f32>>::init_with(..)),
        // ...
    }
}
```

The code provided above serves as an illustrative example. However, employing dynamic dispatch to [erase types](https://doc.rust-lang.org/std/keyword.dyn.html) is indeed beneficial in this scenario.

For the next steps, please provide further details about your use case and what you are aiming to achieve before we go into the design and implementation details.

**Comment by MOZGIII** [comment]
> I don't believe the current design is bad. In fact, quite the opposite! For an overview of Burn's philosophy, please take a look at the [motivation](https://github.com/burn-rs/burn/blob/main/burn-book/src/motivation.md?rgh-link-date=2023-08-27T23%3A56%3A18Z) section. While I wouldn't claim it's flawless, I don't find it to be fundamentally wrong. Additionally, it's important to recognize that different people may have preferences for varying designs with different trade-offs. Functional enthusiasts tend to minimize their use of state and dynamic traits, opting for mappers over mutable data structures. Burn falls somewhere between these two approaches, leaning a bit more towards the functional side with greater emphasis on static dispatch over dynamic dispatch. This isn't indicative of poor design; rather, it brings forth numerous benefits.

At this stage, arguing whether the design is bad or not in abstract terms (i.e. "good but now flawless design") is pointless. I just think we can make it even better. The current approach clearly works, up until it doesn't. It is also restrictive where it can be made not restrictive without losing any important aspects/features of it. That's all I think we have to say about it.

On the absolute scale of things, the current design is indeed pretty good, could be much worse.

> Using an enum for the backend just hide the issue. Consider a scenario where the left-hand side tensor resides in backend 1 (enum variant), while the right-hand side is in backend 2 (another enum variant). In such a situation, the program will compile, but it will lead to a panic! being required, or potentially worse, an implicit backend conversion. This conversion could potentially mask code problems and result in significant performance bottlenecks.

Well, yes, runtime errors can happen if someone switches the implementation mid-flight. If you think it is a problem, well, there is a super-easy fix - wrap the enum into a struct with the enum being a private field. I am actually surprised to see this argument, as it seems so trivial to me.

---

The use case is pretty much to easily go from the code that works with a static backend (see [this](https://github.com/Gadersd/stable-diffusion-xl-burn/blob/d7aa08bed1889caa873b0b5be594a4c02359dc4d/src/bin/sample/main.rs) for an example) to the code that can use any implemented backend at runtime. The idea is to implement the solution on the ecosystem level to have a clear universal set of parameters that are used to tweak the backend aspects at runtime, contrary to having each application implement its own way of configuring this - such that only the actual model parameters would have to be custom-configured.

I am interested in this because this is an important step for making the ecosystem of apps that are built on top of burn more ergonomic to use for manual, Unix-way command-line usage. I do not have a corporate use case here, or anything like that. It is just in Python (and currently in Rust) it sucks that everyone writes their own config for backends, and it is often even broken and/or limited to just the device the author used. This is just... bad. So, what I am trying to achieve at large here is to set the world conditions in such a way that the rust ecosystem of ML doesn't suck in this way that Python does.

To be honest, I'm not an ML dev, and when I read Python code I always wonder how can those people live like that. Of course, there are reasons, and most ML people who write Python code are not concerned with the more generalist software development practices, they are mostly working in an academic setting and writing more of a script than an app - but often their code is scary.

So, yeah, sorry for sharing my frustration, but it is where my use case is rooted in. I just want a better ecosystem.

Of course, burn is already so much better - but there are some pain points that I'd like to relieve.

It would be much better if instead of having to think about and manually add support for things that are easy to generalize and purely technical, people would just import a ready-made implementation that just works and go on with whatever they were doing.

**Comment by antimora** [comment]
Before we proceed with such a significant modification, I'd like to bring up some points that are crucial for my use case. 

I intend to deploy my models to embedded systems and web platforms, and resource constraints are a significant concern for me. In fact, I contributed to making Burn compatible with `no_std` environments to meet these stringent requirements. Performance is a top priority in my use cases, and shifting the backend to use `dyn Trait` objects would introduce performance overheads that are hard to overlook.

When we employ dynamic dispatch through `dyn`, every method call from the model to the backend would require a virtual table lookup. This introduces an additional layer of overhead that I'm keen to avoid. Additionally, dynamic dispatch would prevent the compiler from applying certain optimizations that are only possible when the backend is statically bound, such as function inlining. In essence, switching to a trait object for the backend would multiply these performance disadvantages across the entire model's surface area.

So for me, this proposed change would not be beneficial and would indeed negatively impact the performance of my applications. I kindly request that these considerations be factored into the decision-making process.

**Comment by MOZGIII** [comment]
> I intend to deploy my models to embedded systems and web platforms, and resource constraints are a significant concern for me. In fact, I contributed to making Burn compatible with no_std environments to meet these stringent requirements. Performance is a top priority in my use cases, and shifting the backend to use dyn Trait objects would introduce performance overheads that are hard to overlook.

Yes, this makes perfect sense to me. I envision myself working in a similar performance-sensitive setting, so the performance obviously matters to me as well. To that end, I suggest we create an issue to discuss how can we capture, track and monitor the performance changes in burn throughout the maintenance lifetime. I would avoid doing any work on refactoring the core components without a way to ensure it doesn't harm performance.

It shouldn't (more on this later), but it is nice to be sure.

> When we employ dynamic dispatch through `dyn`, every method call from the model to the backend would require a virtual table lookup. This introduces an additional layer of overhead that I'm keen to avoid. Additionally, dynamic dispatch would prevent the compiler from applying certain optimizations that are only possible when the backend is statically bound, such as function inlining. In essence, switching to a trait object for the backend would multiply these performance disadvantages across the entire model's surface area.

Yes, these are very good points actually. `dyn Trait` indeed has all these properties, and it can be a performance hit. The thing is though the ability to use `dyn Trait` does not mean that you have to use it. The old way of using a single concrete backend definitely shouldn't go anywhere, and all the inlining benefits should remain for the cases where they are needed.

@antimora does it seem reasonable?

That said, without the performance measurements it is a bit hard to say, but I imagine the backends wouldn't be implemented in such a way that the hot paths will go through the dynamic dispatch. Even though the backend itself can sort of be selected and plugged via a dynamic dispatch - I don't see a problem with implementing a backend in such a way that it configures all the computations for a pipeline via a dynamic dispatch, and then does super-fast, inlined and what have you internal computations without the slow dynamic-dispatch commands from the outside. Well, at least that's how I imagine I'd build that.
Of course, for some backends (looking at tch) the dynamic dispatch wouldn't be a big deal due to how they're implemented in the first place - but even that should be able to be changed in the future if needed (we could link with `libtorch` statically and do an lto).

Also, an enum is not free in terms of performance either. Although it still allows inlining, the resulting monomorphised code for each of the calls would be bloated to include all the implementations to allow for runtime switching, which would have an effect on how the CPU cache/instruction loader is utilized. Not necessarily a noticeable effect, and not something to worry about prematurely, but it is a thing. I usually keep those things in mind when working on high-performance code, but not to a degree that I start worrying about them before they actually begin to matter.

**Comment by antimora** [comment]
> Also, building a v-table on a small object isn't a big problem, but the backend trait can have thousands of methods, which may impact performance more than expected.

That's another concern I have for embedded applications: **memory**. I use the ndarray and wgpu backends, and I don't want to bring in _every_ backend method-especially for a heavy kernel backend like WGPU. I doubt Rust will remove dead, unused methods. The virtual table will likely include entries for all methods, as that's expected at runtime. This has been a concern of mine with Burn, particularly when we decided to introduce dynamic graph optimization; I don't want to deploy code that isn't used, which was one of my initial attractions to Burn.

**Comment by antimora** [comment]
Closing this since we discussed the proposed solution and decides not to got this route.
