### ISSUE TITLE
Loss function which changes over time?

### ISSUE THREAD

**Issue by wbrickner** [tracel-ai/burn#712]
I want to be able to modify the strictness of my loss function over time, beginning with "easy" problems and slowly increasing difficulty over the course of training, called "curriculum learning". Difficulty is just one number in `[0, 1]`, and I intend increase it a little bit after each step, saturating at `1`.

I can't figure out how to modify my custom loss module to allow for this. 

The difficulty comes from the `TrainStep` and `ValidStep` traits forcing `fn step(&self, ...) { }` , and in addition no interior mutability wrappers like `Mutex` or `RefCell` are allowed (`Module` not implemented).

Is there some other way? Can we loosen the trait signatures, or implement `Module` for more types?

**Comment by wbrickner** [comment]
Stupid bad solution in the mean time

```rust
#[derive(Module, Debug, Clone)]
pub struct DifficultySchedule {
  step: usize,
  limit: usize
}
impl DifficultySchedule {
  pub fn next(&mut self) -> f32 {
    self.step += 1;
    let s = self.step as f64 / self.limit as f64;
    (s as f32).min(1.0)
  }
}

static SPREAD_SCHEDULE: Mutex<DifficultySchedule> = {
  Mutex::new(DifficultySchedule {
    step: 0,
    limit: 1000
  })
};
```

However, even if I got what I really wanted, this would not suffice, as loss function forward passes from the train and validation steps in the same epoch would get different difficulty levels.

Is there some way to do this properly?

**Comment by wbrickner** [comment]
Stupid bad solution in the mean time

```rust
#[derive(Module, Debug, Clone)]
pub struct DifficultySchedule {
  step: usize,
  limit: usize
}
impl DifficultySchedule {
  pub fn next(&mut self) -> f32 {
    self.step += 1;
    let s = self.step as f64 / self.limit as f64;
    (s as f32).min(1.0)
  }
}

static DIFFICULTY_SCHEDULE: Mutex<DifficultySchedule> = {
  Mutex::new(DifficultySchedule {
    step: 0,
    limit: 1000
  })
};
```

However, even if I got what I really wanted, this would not suffice, as loss function forward passes from the train and validation steps in the same epoch would get different difficulty levels.

Is there some way to do this properly?

**Comment by nathanielsimard** [comment]
`Mutex` and `RwLock` should implement the `Module` trait, we should create an issue for that. But there are other ways to implement your learning technique. I [added recently](https://github.com/burn-rs/burn/pull/689) the possiblity to modify the optimzing step on a module with the `TrainStep`:

```rust
pub trait TrainStep<TI, TO> {
    fn step(&self, item: TI) -> TrainOutput<TO>;
    /// Optimize the current module with the provided gradients and learning rate.
    ///
    /// # Arguments
    ///
    /// * `optim`: Optimizer used for training this model.
    /// * `lr`: The learning rate used for this step.
    /// * `grads`: The gradients of each parameter in the current model.
    ///
    /// # Returns
    ///
    /// The updated model.
    fn optimize<B, O>(self, optim: &mut O, lr: f64, grads: GradientsParams) -> Self
    where
        B: ADBackend,
        O: Optimizer<Self, B>,
        Self: ADModule<B>,
    {
        optim.step(lr, self, grads)
    }
}
```

So, you could override the `optimize` function and call any mutable function directly on your module, no mutex required. 

```rust
impl<B: ADModule> TrainStep<Input, Output> for MyModel<B> {
    fn step(&self, item: TI) -> TrainOutput<TO> {
        ...
    }
    fn optimize<BO, O>(self, optim: &mut O, lr: f64, grads: GradientsParams) -> Self
    where
        BO: ADBackend,
        O: Optimizer<Self, BO>,
        Self: ADModule<BO>,
    {
        let mut module = optim.step(lr, self, grads);
        module.update_learning_difficulty(); // mut method
        module
    }
}
```

Let me know it if helps!

**Comment by nathanielsimard** [comment]
I created #713 to support Mutex and RwLock modules.

**Comment by antimora** [comment]
Closing it since the solution will be in https://github.com/tracel-ai/burn/issues/713
