### ISSUE TITLE
Unfold tensor operation

### ISSUE THREAD

**Issue by nathanielsimard** [tracel-ai/burn#787]
### Feature description

Support the unfold operation. See the PyTorch documentation for full description: https://pytorch.org/docs/stable/generated/torch.nn.Unfold.html#torch.nn.Unfold

**Comment by agelas** [comment]
@nathanielsimard I can try doing this, and I'm assuming you'd want to follow PyTorch's constraint of only allowing 4-dimensional input tensors? If that's the case, how would you get around the constraint of working with dimensionality of D? If I were to do this, I'd start by defining the output tensor with something like `let mut output = Tensor::zeros([N, C * kernel_size[0] * kernel_size[1], H_out * W_out]);`, and then basically it seems like you have to extract "patches" of the current tensor to project into the output, something like this:

```Rust
let patch_tensor: Tensor<B, D, K> = self.select(n, indices);

output = output.select_assign(2, some_other_indices, patch_tensor); // will error because expects a Tensor<_, _, 3> but patch_tensor is Tensor<_, K, D>
```

Is there a way to ensure `self.select(n, indices) returns a Tensor<_, _, 3>` or to cast/convert it appropriately?

**Comment by nathanielsimard** [comment]
@agelas I'm unsure if we can implement this operations efficiently using existing tensor operations. It is similar to a convolution or a pooling operation, which are all implemented by backends with custom kernels.

Maybe we can implement this efficiently using conv2d with a custom weight matrix of ones and zeros, but probably not a `select_assign` or anything index related.
