### ISSUE TITLE
Encounter PythonNotInstalled error when running Burn book example

### ISSUE THREAD

**Issue by an1217** [Tracel-AI/burn#828]
I encountered a PythonNotInstalled error when trying to run the Burn book example. I faced a similar issue with the project example. Do I need to install the Python runtime to resolve this?

**Comment by antimora** [comment]
@an1217, thanks for reporting it. Yes, you will need Python to be installed. We use HuggingFace python library to download datasets for training MNIST. It's only required for this step and any other parts are pure Rust based execution.

CCIng @louisfd. Probably we should also update [the getting started Book section](https://burn-rs.github.io/book/getting-started.html) to tell Python is required too.

**Comment by an1217** [comment]
> ，感谢您的举报。是的，您需要安装 Python。我们使用HuggingFace python库下载数据集以训练MNIST。它只是此步骤所必需的，任何其他部分都是纯粹基于 Rust 的执行。
> 
> CCIng .可能我们还应该更新[入门书籍部分](https://burn-rs.github.io/book/getting-started.html)，以告诉 Python 也是必需的。

Thanks for your reply, after I installed python, I could not get huggingface raise ConnectionError(f"Couldn't reach '{path}' on the Hub ({type(e).__name__})"), Ask which one is used I may need to download the address and copy it to local myself

**Comment by golanguage** [comment]
Hello, @antimora !
In China, Hugging Face service is not availabele., bus it is only supported dataset source, so burn-dataset-0.10.0\src\source\huggingface\mnist.rs will panic with "Couldn't reach '{path}' on the Hub" for Chinese user.

I'm not sure the exact reason. Someone said, " in China Generative AI service must  use real-name management, but obviously  Hugging Face does not". 

And as a possible solution, I know pytorch torchvision dataset lib download MNIST data  from AmasonAWS, which is available in China. Like bellowing :

```
    mirrors = [
        "http://yann.lecun.com/exdb/mnist/",
        "https://ossci-datasets.s3.amazonaws.com/mnist/",
    ]
```

**Comment by antimora** [comment]
> Hello, @antimora ! In China, Hugging Face service is not availabele., bus it is only supported dataset source for Burn, so burn-dataset-0.10.0\src\source\huggingface\mnist.rs will panic with "Couldn't reach '{path}' on the Hub" for Chinese user.
> 
> I'm not sure the exact reason. Someone said, " in China Generative AI service must use real-name management, but obviously Hugging Face does not".
> 
> And as a possible solution, I know pytorch torchvision dataset lib download MNIST data from AmasonAWS, which is available in China. Like bellowing :
> 
> ```
>     mirrors = [
>         "http://yann.lecun.com/exdb/mnist/",
>         "https://ossci-datasets.s3.amazonaws.com/mnist/",
>     ]
> ```

Yeah, unfortunately the logic for the sites are in HuggingFace datasets lib. The best thing that I can recommend is to use a proxy that allows access to huggingface. See, https://discuss.huggingface.co/t/huggingface-not-accessible-to-china/55482

**Comment by golanguage** [comment]
> Yeah, unfortunately the logic for the sites are in HuggingFace datasets lib. The best thing that I can recommend is to use a proxy that allows access to huggingface. See, https://discuss.huggingface.co/t/huggingface-not-accessible-to-china/55482

This link, in fact *.huggingface.co, is not available from  China.

**Comment by antimora** [comment]
Ok. Here is the text from the site:

> you should add proxy on your machine

**Comment by antimora** [comment]
Hugging face is a major site that stores all metadata for the data sources. It is like cargo.io that we rely on to build crates. Duplicating the raw data is not. The pre-processing logic and code is hosted. It is unfortunate for you and I hope you can find a proxy that allows connection.
