### ISSUE TITLE
Can't create tensor with 3 dimensions (Tensor<Backend, 3>) from array [[f32; 3]; 3]

### ISSUE THREAD

**Issue by EnvOut** [Tracel-AI/burn#855]
I have code:
```    let data: [[f32; 3]; 3] = [
        [0.1, 0.1, -0.3],
        [0.1, 0.2, 0.0],
        [0., 1.3, 0.1],
    ];
    
    let weights: Tensor<Backend, 3> = Tensor::from_data(data);`
```    
Compiler raise error: 
```
14  |     let weights: Tensor<Backend, 3, Float> = Tensor::from_data(data);
    |                                              ----------------- ^^^^ the trait `From<[[f32; 3]; 3]>` is not implemented for `Data<f32, 3>`
    ```
    
    Why it happen?

**Comment by AuruTus** [comment]
Seems the float array is just dim 2. Try some mat like [[[0., 1., 2.], [0., 1., 2.], [0., 1., 2.]]] with '.from_data()'.

**Comment by louisfd** [comment]
Indeed, the D generic is somewhat misnamed, as it does not represent dimension sizes but the **rank** of the tensor, i.e. the number of nested brackets. 
You can probably just change 3 to 2.

**Comment by antimora** [comment]
@EnvOut please let us know if @louisfd suggestion has resolve the issue?

**Comment by antimora** [comment]
Closing this as resolved.
