### ISSUE TITLE
Add element-wise minimum and other element-wise operations for tensors

### ISSUE THREAD

**Issue by EddieMataEwy** [tracel-ai/burn#856]
### Feature description

Element wise functions such as getting the minimum element-wise of 2 tensors. Like torch.minimum().

### Feature motivation

Right now to do element wise minimum of 2 tensors I believe I need to do:
`tensor_1.clone().mask_where(tensor_2.clone().lower(tensor_1.clone()), tensor_2.clone())`
It would be better to do something like:
`let minimum = Tensor::min(tensor_1, tensor_2)`
Another example would be the clamp function, which can clamp the tensor only by fixed numbers and you would have to apply a couple similar `mask_where` as in the previous example.

### (Optional) Suggest a Solution

I think we should find which of these functions are missing first, and then depending on the optimization complexity we can implement them directly or do a simple wrap like the example provided.
Do you agree?

**Comment by louisfd** [comment]
Hi @EddieMataEwy 
Thanks for the suggestion. 

The clamp functions already exist, they have this default implementation (clamp_min shown here):
```
let mask = Self::lower_elem(tensor.clone(), min);
B::mask_fill(tensor, mask, min)
```
And then for every backend we are free to re-implement it, like it is done in the torch backend where the torch clamp functions are called, or not, like in WGPU for now, so it falls back to using lower_elem and mask_fill. 

We could do this strategy for binary min and max, using the line you suggested as a default implementation, then re-implementing it for every backend will be a fun optimization to do. 

I'll tag this feature as a good first issue as you can inspire yourself from clamp.

**Comment by EddieMataEwy** [comment]
I think we should also consider the possibility of allowing broadcastable tensors on some of these functions.
Say we want to clamp tensor_1 with tensor_2 as the lower value and with the number 3 as the higher value.
We could create a tensor full of 3s with the same size or allow a tensor of the same type with a single element 3 that will be used in all comparisons.
Of course, broadcastable tensors could have more elements.

What do you think?

Maybe we can decide on that down the road and focus on same size tensors first.

**Comment by louisfd** [comment]
I believe we could repeat the pattern used for some other ops like addition. For addition we have both add and add_scalar. The former sums two tensors of rank D element-wise (with support for broadcast) and the former adds a scalar to every element. An advantage of this is that, for the scalar version, we do not have to launch a computation kernel with two tensor buffers as inputs, we can use a unary operation. So the result would be:
`tensor_1.clamp_min(tensor_2).clamp_max_scalar(3.)`

**Comment by EddieMataEwy** [comment]
That does sound like the most reasonable approach.
It would break backwards compatibility, so I would like to know other people's opinion on this.

**Comment by WorldSEnder** [comment]
I'm searching for this functionality too. Note that simply masking and replacing some elements can have different behaviour on an autodiff backend. See [similar issue in pytorch](https://github.com/pytorch/pytorch/issues/56734) that notes

> amax/amin evenly distributes gradient between equal values

With `let t3 = Tensor::min(t1, t2)`, I would expect that for elements with `t1[i] == t2[i]` (or, well, up to some epsilon), that the gradient gets split between the two inputs. Technically, of course the function is not differentiable at the point, but evenly splitting seems like a fair choice. If I'm reading the [current impl](https://github.com/tracel-ai/burn/blob/57887e7a4747b1ba52e79fd16a3744bc5da67607/crates/burn-autodiff/src/ops/tensor.rs#L1179-L1190) of `mask_where` correctly, every gradient is only propagated along one of the inputs.

**Comment by nathanielsimard** [comment]
> I'm searching for this functionality too. Note that simply masking and replacing some elements can have different behaviour on an autodiff backend. See [similar issue in pytorch](https://github.com/pytorch/pytorch/issues/56734) that notes
> 
> > amax/amin evenly distributes gradient between equal values
> 
> With `let t3 = Tensor::min(t1, t2)`, I would expect that for elements with `t1[i] == t2[i]` (or, well, up to some epsilon), that the gradient gets split between the two inputs. Technically, of course the function is not differentiable at the point, but evenly splitting seems like a fair choice. If I'm reading the [current impl](https://github.com/tracel-ai/burn/blob/57887e7a4747b1ba52e79fd16a3744bc5da67607/crates/burn-autodiff/src/ops/tensor.rs#L1179-L1190) of `mask_where` correctly, every gradient is only propagated along one of the inputs.

The gradients are propagated for the value and the tensor, but not for the mask, though it might not be the behavior you need.

**Comment by antimora** [comment]
@louisfd , @nathanielsimard , @laggui, I think we have this now, right? 

[Element wise min/max between a pair of tensors PR](https://github.com/tracel-ai/burn/pull/1385)

**Comment by antimora** [comment]
I think this is done via min_pair and max_pair ops.
