### ISSUE TITLE
[Tensor operation] Stack

### ISSUE THREAD

**Issue by miestrode** [Tracel-AI/burn#864]
*From what I can tell there isn't a built-in operation for this, but I may be wrong due to being inexperienced*

### Feature description

I would describe the feature, but it's already well-known and implemented in several libraries. See for example the Tensorflow documentation for [`tf.stack`](https://www.tensorflow.org/api_docs/python/tf/stack).

**Comment by jmintb** [comment]
If this turns out to be unimplemented can I work on it? :)

**Comment by antimora** [comment]
@jmintb Yes!
