### ISSUE TITLE
burn-import: ConvTranspose support

### ISSUE THREAD

**Issue by npatsakula** [Tracel-AI/burn#883]
### Feature description

[ConvTranspose](https://onnx.ai/onnx/operators/onnx__ConvTranspose.html) support for `burn-import` ONNX converter.

### Feature motivation

I've tried to port [onnx-ocr](https://github.com/kuroko1t/onnx-ocr) to `burn-rs` using `burn-import` and stuck without support of `ConvTranspose` (two-dimensional version).

### Suggest a Solution

I tried to add support by myself and stuck with proper support of constant weights (see my [PR](https://github.com/burn-rs/burn/pull/884)).

**Comment by npatsakula** [comment]
Hello @antimora!

Thank you for #1018.

**Comment by antimora** [comment]
@npatsakula, it has been successfully merged.

I recommend looking into my SqueezeNet ONNX conversation model: [SqueezeNet-Burn](https://github.com/Tracel-AI/models/tree/main/squeezenet-burn). Note that SqueezeNet is primarily an image classification model. This version has examples of how to feed an image and utilizes an image normalizer, similar to what [onnx-ocr](https://github.com/kuroko1t/onnx-ocr) employs. 

I'm eager to see what you develop. If you're interested, we could host the model here: [Tracel-AI Models](https://github.com/Tracel-AI/models). The ONNX file could be downloaded during a build process (using build.rs). I'd be happy to contribute as well.

CC: @nathanielsimard, @Luni-4

**Comment by npatsakula** [comment]
> @npatsakula, it has been successfully merged.
> 
> I recommend looking into my SqueezeNet ONNX conversation model: [SqueezeNet-Burn](https://github.com/Tracel-AI/models/tree/main/squeezenet-burn). Note that SqueezeNet is primarily an image classification model. This version has examples of how to feed an image and utilizes an image normalizer, similar to what [onnx-ocr](https://github.com/kuroko1t/onnx-ocr) employs.
> 
> I'm eager to see what you develop. If you're interested, we could host the model here: [Tracel-AI Models](https://github.com/Tracel-AI/models). The ONNX file could be downloaded during a build process (using build.rs). I'd be happy to contribute as well.
> 
> CC: @nathanielsimard, @Luni-4

@antimora, thank you a lot!

I used your SqueezeNet wrapper as a source of inspiration. Unfortunately I'm a little stuck with inference results post-processing (onnx-ocr makes heavy use of PaddleOCR internals; I just don't have time to look at it properly). I plan to to get to working on this after the New Year.

I'm planning to use onnx-ocr burn wrapper for two purposes:

1. As part of experimental unified inference backend at my work.
2. As part of my DYI GPhotos pet project (I'm planning to open source it in Q3 2024).

**Comment by antimora** [comment]
Linking to the issue to port into burn/models: https://github.com/tracel-ai/models/issues/23
