### ISSUE TITLE
Autotune: benchmarks cached on disk

### ISSUE THREAD

**Issue by louisfd** [tracel-ai/burn#911]
The autotune mechanism uses a cache to check if, for a specific operation on an input size within a specific range, the benchmarks have already been computed. If so, the fastest operation in that setting on your machine is stored in the cache and we just use this one. That way, it is likely only in the beginning of training/inference that we need to run benchmarks, and then the cache allows for reuse. 

However, the cache is stored in RAM, which means the benchmarks will be recomputed for every new execution, although they will likely reproduce the same results when run on the same machine. 

By storing the cache and/or all benchmark results in a file on disk, we will avoid the computation of benchmarks at every execution. 

We should invalidate the cache when the burn version is different.
The on disk key should be the autotune key + the device from the compute client.

**Comment by nathanielsimard** [comment]
From tuner in burn-compute:

```rust
 fn autotuning(
        &mut self,
        autotune_operation_set: Box<dyn AutotuneOperationSet<S::AutotuneKey>>,
        client: &ComputeClient<S, C>,
    ) -> Box<dyn AutotuneOperation> {
        let key = autotune_operation_set.key();
        let autotunables = autotune_operation_set.autotunables();
        let mut names = Vec::with_capacity(autotunables.len());

        // Run all autotune benchmarks
        let results: Vec<BenchmarkDurations> = autotunables
            .into_iter()
            .map(|op| {
                names.push(op.name().to_string());
                self.run_benchmark(op, client)
            })
            .collect();

        for (name, result) in names.iter().zip(results.iter()) {
            log::info!("Benchmark result {name}-{key} => {result}");
        }

        // Finds the fastest operation, stores it and returns it
        let fastest_index = self.find_fastest(results);
        let fastest_name = names.get(fastest_index).unwrap();
        log::info!("Fastest result {fastest_name}-{key}");

        self.tune_cache.cache_insert(key, fastest_index);
        match self.tune_cache.try_cache(autotune_operation_set) {
            super::TuneCacheResult::Hit(ops) => ops,
            super::TuneCacheResult::Miss(_) => panic!("We just inserted, should not miss"),
        }
    }
```

We should cache the result durations on disk and load them if present to avoid recomputing the benchmarks.
