### ISSUE TITLE
examples/image-classification-web：No response when executing script  './run-server.sh' 

### ISSUE THREAD

**Issue by lebron8dong** [Tracel-AI/burn#917]
**Describe the bug**
when executing script './build-for-web.sh' :
[INFO]: Installing wasm-bindgen...
[INFO]: Optional fields missing from Cargo.toml: 'description', 'repository'. These are not necessary, but recommended
[INFO]: License key is set in Cargo.toml but no LICENSE file(s) were found; Please add the LICENSE file(s) to your project directory
[INFO]: :-) Done in 2m 00s
[INFO]: :-) Your wasm pkg is ready to publish at E:\webgpu\burn-main\examples\image-classification-web\pkg/no_simd.

And no response when executing script  './run-server.sh' .

**Desktop (please complete the following information):**
 - OS: win10
 - Browser：chrome canary

**Additional context**

**Comment by antimora** [comment]
@Luni-4 is working on migrating the script to xstask (see #851) so that it works the same across platforms including Windows. I am on Mac, so I can't verify why it's failing. 

If you'd like to see the demo live, I have temporarily hosted here: https://antimora.github.io/image-classification/

**Comment by antimora** [comment]
Closing this as it will be fixed by https://github.com/Tracel-AI/burn/issues/851
