### ISSUE TITLE
Move more repeated functions and traits into `burn-common` crate

### ISSUE THREAD

**Issue by Luni-4** [tracel-ai/burn#945]
### Feature description

The `burn-common` crate should contain all those functions and traits which are repedetely used within all the other `burn` crates. These functions can be used for tests and benchmarks contexts as well,

### Feature motivation

To reduce boilerplates and avoid repetitions in the code. In addition, this crate can expose some of these methods and traits as public APIs such that other projects can use them as well.  

### (Optional) Suggest a Solution

Possible strategy to improve `burn-common` crate:

1. [ ] Find all repeated functions and traits definition scattered through `burn` crates
2. [ ] Move all of them in `burn-common` crate
3. [ ] Replace the repeated functions and traits call with the ones contained in the `burn-common` crate
4. [ ]  Optimize these functions with `#[inline]` and `#[inline(always)]` attributes

**Comment by nathanielsimard** [comment]
@Luni-4 We already have `burn-common` for stuff that is shared between crates. Utils are normally very dangerous, since everything can go there, everything will go there 😅

**Comment by Luni-4** [comment]
@nathanielsimard 

Thank you for pointing me to the right directory! Yeah, we can use `burn-common` an apply the strategy described above. I agree!

**Comment by antimora** [comment]
Closing it as too open ended. We will do as we refactor one by one.

**Comment by Luni-4** [comment]
Yep, I agree, thanks @antimora!
