### ISSUE TITLE
Building phase fails on `Linux` with `--all-features` option is enabled

### ISSUE THREAD

**Issue by Luni-4** [Tracel-AI/burn#951]
**Describe the bug**

When I try to build `burn` on `Linux` with `--all-features` option enabled I get the following error

```
error: library kind "framework" is only supported on Apple targets
```

**Comment by antimora** [comment]
I don't think it's possible to fix because Burn has mutually exclusive feature flags in ndarray array.

**Comment by Luni-4** [comment]
@antimora 

Perhaps we can try this approach https://users.rust-lang.org/t/how-can-i-enable-rusts-cargo-features-to-compile-code-conditionally-based-on-operating-system/82143/2: enabling features depending on the operating system.
