### ISSUE TITLE
Enable accelerate feature flag in candle for Macs

### ISSUE THREAD

**Issue by antimora** [Tracel-AI/burn#968]
Enable accelerate feature flag in candle for Macs.

from Laurent Mazaré: 

> to mention that you may want to enable the accelerate feature on macos (or provide a way for your users to do so), on macos native builds it makes quite a large differences on matmuls.

**Comment by dcvz** [comment]
Just to note, as a precursor to this we would have to in general start supporting `Metal` in the `candle` backend which we don't atm.

**Comment by antimora** [comment]
> Just to note: as a precursor to this we would have to in general start supporting `Metal` in the `candle` backend which we don't atm.

The Candle author said [accelerate](https://developer.apple.com/documentation/accelerate?language=objc) is separate than Metal: 

<img width="865" alt="image" src="https://github.com/Tracel-AI/burn/assets/939125/7a0b2fed-a8ff-4df2-84a4-15298baaa6ce">

Link to the convo: https://discord.com/channels/1038839012602941528/1091798349247676546/1175892096088031274
