### ISSUE TITLE
Add `interpolate2d` / `upsample_nearest2d` Tensor Method

### ISSUE THREAD

**Issue by dcvz** [Tracel-AI/burn#971]
### Feature description

Add a `interpolate2d` (sometimes also called `upsample_nearest2d`) method on tensor to faciliate splitting a tensor into a given number of chunks

### Feature motivation

Its a fairly common operation supported by other ML frameworks.

**Comment by antimora** [comment]
We already have an existing ticket: https://github.com/Tracel-AI/burn/issues/455

If the existing ticket covers the exact things expected in this ticket, you may close it as dup.

**Comment by dcvz** [comment]
Yes, that covers it! Looks like my search failed. Might've just searched upsample. Closing!
