### ISSUE TITLE
 Implement scheduled action for scanning unused dependencies

### ISSUE THREAD

**Issue by antimora** [Tracel-AI/burn#975]
**Description**:

This issue focuses on setting up a scheduled action to regularly scan for unused dependencies (`udeps`) in our project. The aim is to ensure efficient dependency management without hindering the continuous integration process.

**Background**:

- Our current setup with `udeps` has been causing build failures due to unresolved false positives in the CI pipeline.
- The proposal to disable `udeps` temporarily raised concerns about the long-term management of dependencies.
- An alternative approach has been suggested to handle this through scheduled scans, similar to our security scans.

**Proposal**:

Instead of disabling `udeps` or moving its checks to the `publish.yml` script, we propose setting up a scheduled action. This action will regularly scan the repository for unused dependencies. This approach aims to maintain a clean dependency list without impacting the regular development flow.

**Advantages**:
- **Non-Blocking Development**: Developers can continue working without being blocked by `udeps` failures in CI.
- **Regular Maintenance**: Regular scans ensure that dependency management is an ongoing process rather than a last-minute rush before releases.
- **Early Detection**: Helps in identifying and resolving dependency issues early in the development cycle.

**Implementation Considerations**:

1. **Schedule Frequency**:
   - Determine how frequently the scan should run (e.g., weekly, bi-weekly).
   
2. **Scope of Scans**:
   - Decide if scans should cover the entire repository or specific modules.

3. **Handling Scan Results**:
   - Establish a protocol for addressing issues found during scans, including assigning responsibilities for resolving them.

4. **Integration with CI/CD**:
   - Ensure the scheduled action is seamlessly integrated with our existing CI/CD pipeline.

**Action Items**:
- [ ] Determine the optimal frequency for the scheduled `udeps` scans.
- [ ] Define the scope and parameters of the `udeps` scans.
- [ ] Develop a workflow for handling and addressing issues identified in the scans.
- [ ] Integrate the scheduled scan action into the existing CI/CD system.

**Additional References**:
- Related Discussions: [Disable udeps checking till all unused deps are resolved #969](https://github.com/Tracel-AI/Tracel-AI/pull/969), [Fix image classifier build failure by upgrading versions #967](https://github.com/Tracel-AI/Tracel-AI/pull/967)
- Example of False Positive Handling: `burn/burn-dataset/Cargo.toml` (lines 55-56).

**Comment by Luni-4** [comment]
@antimora 

This approach is great! Thank you for describing the process in detail! Feel free to assign me to this task!
