### ISSUE TITLE
not support c++17

### ISSUE THREAD

**Issue by wx2480** [Tracel-AI/burn#981]
**Describe the bug**

my machine only support c++11, but the torch-sys request c++17, so what should i do to to run the mnist example?

**Comment by antimora** [comment]
You could run with another backend, such as NDarray or WGPU if you cannot use torch. For more specifics regarding C++ tooling requiring, you'll need to seek out the tch support: https://github.com/LaurentMazare/tch-rs, which is used as a dependency for burn-tch. 

I'll close this ticket for now. Let us know if you need more assistance.
