### ISSUE TITLE
Module Does Not Support Tensor<B, D, Int>

### ISSUE THREAD

**Issue by dcvz** [Tracel-AI/burn#982]
**Describe the bug**
For some reason Module structs do not allow having a Tensor of Kind = Int.

**Screenshots**

![Nov 21 Screenshot](https://github.com/Tracel-AI/burn/assets/2475932/5da1eea8-c0de-48e8-b219-be00cc8b3e55)

![Screenshot_2023-11-21_at_13 53 30](https://github.com/Tracel-AI/burn/assets/2475932/737e536e-85ac-430d-8112-18276f5a0336)

**Comment by antimora** [comment]
This should be fixed now.

**Comment by dcvz** [comment]
Can confirmed as fixed!
