### ISSUE TITLE
Module Cannot Be Derived in Enum

### ISSUE THREAD

**Issue by dcvz** [Tracel-AI/burn#983]
**Describe the bug**
I'm facing an issue where I can't successfully derive Module in an Enum.

**To Reproduce**
Create a similar enum:

```rust
#[derive(Module, Debug)]
pub enum Activation<B: Backend> {
    Gelu,
    QuickGelu,
    GeluErf,
}

impl Activation {
    pub fn forward<B: Backend, const D: usize>(&self, xs: Tensor<B, D>) -> Tensor<B, D> {
```

**Expected behavior**
It should work. 

**Screenshots**

![Nov 21 Screenshot (1)](https://github.com/Tracel-AI/burn/assets/2475932/74918108-d5e8-4b28-9435-e73aa1b3614c)

**Comment by antimora** [comment]
Thanks for filing. Yes, currently it is not fully implemented. We have an outstanding ticket regarding this: https://github.com/Tracel-AI/burn/issues/726
