### ISSUE TITLE
Add `triu` and `tril` Tensor Method

### ISSUE THREAD

**Issue by dcvz** [Tracel-AI/burn#986]
### Feature description

Add a `triu` and `tril` methods to return the upper/lower of a matrix (2-D tensor) or batch of matrices, while setting the rest to 0.

### Feature motivation

Operation supported by other ML frameworks

**Comment by antimora** [comment]
Added `tril` as well

**Comment by dcvz** [comment]
@antimora can you assign me here?

**Comment by antimora** [comment]
> @antimora can you assign me here?

Done!

**Comment by dcvz** [comment]
PR for this now submitted #1002

**Comment by antimora** [comment]
Closing as the PR is merged now.
