### ISSUE TITLE
discord link not working

### ISSUE THREAD

**Issue by scfurl** [Tracel-AI/burn#994]
Thanks for a great library!  I can't seem to get the Discord link to work...

<img width="784" alt="image" src="https://github.com/Tracel-AI/burn/assets/16267955/31c42306-5451-49ab-8d34-c4458771a4ef">

**Comment by antimora** [comment]
@nathanielsimard @louisfd I am traveling. Can you you please fix this.

**Comment by louisfd** [comment]
Thanks for letting us know, I fixed it
