### ISSUE TITLE
Unable to run examples or build on M1 Mac

### ISSUE THREAD

**Issue by michael-long88** [Tracel-AI/burn#999]
**Describe the bug**

When trying to run `cargo build` on the clone `burn` repo, or when running an example like `cargo run --example ag-news-train --release --features tch-cpu`, I get the following output:
```
error: Package `burn-dataset v0.11.0 (/Users/michaellong/Projects/burn/burn-dataset)` does not have feature `rusqlite`. It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.
```

**To Reproduce**

1. Clone the repo with `git clone https://github.com/burn-rs/burn.git`
2. `cd burn`
3. cargo run --example ag-news-train --release --features tch-cpu

**Expected behavior**

Example should run.

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.1.1
 - Hardware: M1 Mac Pro 16GB

**Comment by dcvz** [comment]
I just tried running `cargo run --example ag-news-train --release --features tch-cpu` from the checked out repo and dit seems to have started running. I did eventually git a `segmentation fault` though but that seems to be different than what you're reporting here.

What branch are you running this from?

**Comment by nathanielsimard** [comment]
I think it might be related to a different version of Rust (maybe nightly?)

**Comment by michael-long88** [comment]
It was definitely the version of Rust I was running. I was running `1.70`, but upgrading to `1.74` fixed it. That's totally on me for not seeing the `1.71.0+` requirement in the README. Thanks for the help!
